### ISSUE TITLE
gplaycli credentials method doesn't work

### ISSUE THREAD

**Issue by valvin1** [matlink/gplaycli#101]
Operating System : Ubuntu 16/04 
Python : Python 2.7.12
Gplaycli : GPlayCli version 0.2.10

Install method : pip2 install gplaycli

when using `Token=False` with good credentials i have the following error when typing gplaycli -v : 

```
Using credentials to connect to API
Using plaintext password
Cannot login to GooglePlay ( server says: BadAuthentication ), remaining tries 9
Using credentials to connect to API
Using plaintext password
Cannot login to GooglePlay ( server says: BadAuthentication ), remaining tries 8
```
I've double checked my credentials and tried several android_id

I need this method because token method doesn't allow me to download some apps like Somfy Protect : `com.myfox.android.mss`

When I search using gplaycli it doesn't appear. But I'm abble for example to get it throught Yalp.

In that case : 

```
○ → gplaycli -s "somfy protect"
Title                               Creator                              Size    Downloads  Last Update    AppID                                   Version  Rating  
Myfox Security Application          Somfy Protect by Myfox SAS           47.2MB  1 000+    6 avr. 2017    com.myfox.android.msa                   1010     4.23    
ALARME SOMFY                        Somfy SAS                            19.4MB  10 000+   20 janv. 2017  fr.somfy.homemotion                     30       2.82    
Connexoon Window                    SOMFY SAS                            19.9MB  10 000+   13 juil. 2017  com.somfy.connexoon_window              16       3.07    
Xiomfy 4                            SkyDev                               2.7MB   1 000+    3 sept. 2017   com.skydev.xiomfy                       35       4.62    
Somfy – Curtain configurator      Abastra Sp. z o.o.                   4.8MB   100+       14 juil. 2017  com.abastra.somfyee                     9        3.50    
Handwerker Notdienst Niedersachsen  handwerkernotdienstniedersachsen.de  2.4MB   1 000+    10 févr. 2017 net.ays.PROD289621                      381      3.89    
MyUbiwizz                           UBIWIZZ                              24.0MB  50+        25 juil. 2017  com.decelect.ubiwizz                    1018     0.00    
Belkin NetCam                       Belkin                               14.8MB  100 000+  6 sept. 2016   com.belkin.android.androidbelkinnetcam  112      3.38    

```

com.myfox.android.msa is the old one.

The good one is [here](https://play.google.com/store/apps/details?id=com.myfox.android.mss) on PlayStore

This package is only an example I had a lot of others.

**Comment by matlink** [comment]
Duplicate https://github.com/matlink/gplaycli/issues/94

**Comment by valvin1** [comment]
@matlink there is 2 issues in one. Effectively the first part is a duplicate of #94 but i'm not sure for the second. 

Issue is that using token method I do not access to all apps. Example package is not displayed in search and download fails. 

Does someone can tell me if this package is available using `gplaycli -s` or `gplaycli -d` ?
