### ISSUE TITLE
Password encryption and new APIs

### ISSUE THREAD

**Issue by NoMore201** [matlink/gplaycli#103]
In my python3 fork[0] of googleplay-api, I implemented the following features:

* Password encryption
* Ac2dm token
* New APIs for download and search
* More recent headers, referencing a OnePlus One as device 

The code needs more testing and enhancements, but overall it is working fine (thanks to [play-store-api](https://github.com/yeriomin/play-store-api) and [this](https://github.com/subtletech/google_play_store_password_encrypter) ruby implementation).
Since the code is written for python3, and there are quite some changes in googleplay-api structure, I prefer to wait for a pull request and discuss this changes here (or in another place if this is not the right one) if you are interested.

[0] https://github.com/NoMore201/googleplay-api

**Comment by matlink** [comment]
thanks a lot ! I tried to implement it myself some time ago, unsuccessfully.
That means 2 things: I'll be able to fix credentials auth issue and write a python 3 gplaycli.
I'll check it out when I can.
Thanks again :)
