### ISSUE TITLE
Apps installed from downloaded apk still showing as not up-to-date

### ISSUE THREAD

**Issue by psycholyzern** [matlink/gplaycli#104]
I have limited bandwidth on my mobile data, so I usually download APKs on my renote server and transfer them into cloud (free bandwidth given by my ISP) which I would download to my phone later.  
  The problem is, even if I installed the latest APK, playstore still showing that app as outdated even the version installed is matched with the latest version in Playstore. Cleared app data of Playstore and still wont fix.  
  The weirder thing is, I downloaded the same version from apkmirror.com, installed it over the previous fetched apk, Playstore will say I have latest version. Why Playstore think I have an outdated app when I installed latest version already from gplaycli? But somehow it recognize apk from apkmirror as latest?

**Comment by matlink** [comment]
once you installed the gplaycli version of your apk file on your phone, check the app version in settings. 
check if the version is the same when installing the apkmirror apk file. I guess they are not the same.
gplaycli sometimes has not the latest version of an app, because the device it simulates neither have it. apkmirror is known to be able to fake many devices, and then often has the latest version.

**Comment by psycholyzern** [comment]
Unfortunately the version is the latest. It bothers me for quite long until I tried installing the same version fetched from apkmirror. I just finished installing Facebook apk before opening this issue.  
I will try to reproduce with other app and update about them here later. 
Thanks

**Comment by matlink** [comment]
make a checksum (sha256) of both apk and verify they are the same

**Comment by psycholyzern** [comment]
The file downloaded from apkmirror is bigger than the one downloaded using gplaycli
[20170917_230957.jpg](https://postimg.org/image/bqjjly8xp/)

**Comment by psycholyzern** [comment]
I did another test on Chrome. 6 images were uploaded here: [https://postimg.org/gallery/39k4pjp3y/](https://postimg.org/gallery/39k4pjp3y/)  
  
Image:
1 - Playstore show Chrome as outdated.
2 - Latest version on my Playstore is 60.0.3112.116
3 - Version installed is also 60.0.3112.116
4 - Showing both apk from gplaycli and apkmirror respectively.
5 - Message shown when trying to install apkmirror's version over gplaycli. Both are the same latest version. 
6 - Playstore show Chrome as uptodate after installed apk from apkmirror.

**Comment by matlink** [comment]
The funny thing is that apkmirror uses gplaycli to download apks. 
What's your phone?

**Comment by archon810** [comment]
That's not entirely accurate @matlink. The majority of APKs are uploaded by our users.

**Comment by psycholyzern** [comment]
@matlink my phone is OnePlus One.

**Comment by matlink** [comment]
That's because Gplaycli is using `angler's (nexus 6P, api 23) ` `device.properties` for which chrome is not upgradeable.

**Comment by psycholyzern** [comment]
Can I change it?

**Comment by matlink** [comment]
For now, no. #70 needs to be done.

**Comment by matlink** [comment]
Now you can with release 3.3
