### ISSUE TITLE
change in version scheme

### ISSUE THREAD

**Issue by ford--prefect** [matlink/gplaycli#106]
Did you intentionally jump from 0.2.13 to 2.14? If I follow this versioning scheme for packaging there is no real way back…

**Comment by matlink** [comment]
yes it was intended. It's easier to manage since 0.something is useless I think.
However I don't get your concern. Could you detail a bit more?

**Comment by ford--prefect** [comment]
I am packing the software for the AUR (Archlinux User Repository), going back to lower version numbers is not foreseen there.
Thanks for the confirmation, I'll upload the build script for the new verison soon.
