### ISSUE TITLE
cannot download game error "list index out of range"

### ISSUE THREAD

**Issue by jr3074** [matlink/gplaycli#107]
hello @matlink ,
is there any update? since yesterday i cannot download game using this app. the error code is "list index out of range"

**Comment by jr3074** [comment]
i think the problem is android_ID, i changed it so i can download, but i still cannot download some apps.
but why this happened?
yesterday it works great with my android_ID but today i cannot download so many apps

**Comment by jr3074** [comment]
Operating System debian jessie
python 2.7.9
latest gplaycli
using pip install gplaycli

**Comment by matlink** [comment]
are you using the token or your own credentials ?

**Comment by jr3074** [comment]
i'm using my token,

**Comment by jr3074** [comment]
i also tried your token (default config), got same issue, cannot download some apps/games like mobile legend, criminal case, and more

**Comment by NoMore201** [comment]
I think this problem is related to old search() and download() APIs, as I already stated in this issue:

https://github.com/matlink/gplaycli/issues/99#issuecomment-333875712

The gpapi library should be updated in order to solve those issues.

**Comment by matlink** [comment]
Please check again with version 3.2 of Gplaycli
