### ISSUE TITLE
App not found after search

### ISSUE THREAD

**Issue by raphael0202** [matlink/gplaycli#11]
I tried to download the "La banque postale" app:
https://play.google.com/store/apps/details?id=com.fullsix.android.labanquepostale.accountaccess

But it is not found after search:

    [raphael@alarmpi gplaycli]$ ./gplaycli -s "La banque postale"
    Title                           Creator                                      Size     Downloads   Last Update
    AppID                                    Version  Rating  
    Caf - Mon Compte                Caisse nationale des Allocations familiales  732.5KB  1 000 000+22 juil. 2015  fr.cnaf.mobile.moncompte                 5        3.91    
    ameli, l'Assurance Maladie      Caisse Nationale d'Assurance Maladie         10.6MB   1 000 000+29 avr. 2015   fr.cnamts.it.activity                    601      3.91    
    Leboncoin                       LBC France                                   10.1MB   5 000 000+6 août 2015   fr.leboncoin                             28500    4.18    
    Application mobile Pôle emploi Pôle emploi                                 4.9MB    1 000 000+2 avr. 2015    com.poleemploi.pemobile                  312      3.33    
    Mes Paiements                   La Banque Postale                            8.5MB    50 000+    29 juin 2015   com.lbp.peps                             11       3.28    
    Prépayé par la Banque Postale La Banque Postale                            3.2MB    10 000+    18 mars 2015   ppc.mobile.app.client                    6        3.28    
    Banque                          Caisse d'Epargne                             8.8MB    1 000 000+19 mars 2015   com.caisseepargne.android.mobilebanking  25       4.05    
    Impots.gouv                     Direction générale des Finances publiques  1.7MB    500 000+   28 avr. 2015   fr.gouv.finances.smartphone.android      25       3.21    
    Ma Banque                       CREDIT AGRICOLE TECHNOLOGIES ET SERVICES     41.9MB   1 000 000+20 juil. 2015  fr.creditagricole.androidapp             32       3.83    
    Run Sackboy! Run!               PlayStation Mobile Inc.                      292.1MB  1 000 000+8 avr. 2015    com.playstation.runsackboyrun            42       4.19

Trying to download it using its ID does not work either:

    [raphael@alarmpi gplaycli]$ ./gplaycli -d com.fullsix.android.labanquepostale.accountaccess
    Error while downloading com.fullsix.android.labanquepostale.accountaccess : this package does not exist, try to search it via --search before

**Comment by matlink** [comment]
Duplicate of #5, try to use default credentials, and check if you can search & download your app.

**Comment by raphael0202** [comment]
I used default credentials

**Comment by matlink** [comment]
I can't download it too, androidID seems not to be compatible with it. Can you try generate another one ? Check readme for it :)

**Comment by raphael0202** [comment]
The app can now be downloaded (change of default AndroidID?)
