### ISSUE TITLE
Paid apps download

### ISSUE THREAD

**Issue by BiatuAutMiahn** [matlink/gplaycli#111]
OS=Ubuntu 16.10
Ver=3.0 [Python.2.7.12+]
Install=
```
git clone (.../commit/7182ef8f04046b004be19a28677a95c43845afdb) //due to latest failing build
sudo pip install ./gplaycli

```
Auth=Own (Token URL from template config)

Unable to download my purchased apps, throws error:
`Error while downloading it.android.demi.elettronica.pro : 'GooglePlayAPI' object has no attribute 'delivery'`

**Comment by matlink** [comment]
For now use version 2.16: `git checkout 2.16 && sudo pip install . --upgrade'

**Comment by BiatuAutMiahn** [comment]
List index out of range on 2.16, ill wait for patch as it seems to just be a mismatched property

**Comment by matlink** [comment]
It is fixed in the `master` branch of `googleplay-api`.
If you want to patch it now, run `git clone https://github.com/nomore201/googleplay-api && sudo pip install googleplay-api` or wait for maintainer to push it to pypi.

**Comment by BiatuAutMiahn** [comment]
ty, however with your latest passing build, errors are being thrown @ get_cached_token, "ValueError: need more than 1 value to unpack"

**Comment by BiatuAutMiahn** [comment]
Scratch that, I wiped out ~/.cache/gplaycli and it worked

**Comment by BiatuAutMiahn** [comment]
Says "App not purchased" it is indeed purchased

**Comment by matlink** [comment]
remember to use your credentials then, otherwise you're using the token from my accounts

**Comment by BiatuAutMiahn** [comment]
umm, I am using my own credentials in /etc/gplaycli/gplaycli.conf, my email and password. I tried with 2.16, and it says list index out of range. tried with latest branch and it says app not purchased.  

Screenshot:
[https://infinitycommunicationsgateway.net/pub/screens/2017.10.07-%20Screen.png](https://infinitycommunicationsgateway.net/pub/screens/2017.10.07-%20Screen.png)

**Comment by matlink** [comment]
please post here the output of 
```
gplaycli -v -pd it.android.demi.elettronica.pro
```

**Comment by BiatuAutMiahn** [comment]
```
GPlayCli version 2.16 [Python2.7.12+] 
Configuration file is /home/biatu/.config/gplaycli/gplaycli.conf
Retrieving token ...
Token: QQUcMVDtJoP4ZW3siD9iJQWoLBN7AEVLqhzLmL1a_bixPYUiHdg79NawigR3ycNR8CQQNg.
Using token to connect to API
1 / 1 it.android.demi.elettronica.pro
Error while downloading it.android.demi.elettronica.pro : this package does not exist, try to search it via --search before
A few packages could not be downloaded :
it.android.demi.elettronica.pro
list index out of range
```

Commit 1888c60
```
GPlayCli version 3.0 [Python2.7.12+] 
Configuration file is /home/biatu/.config/gplaycli/gplaycli.conf
Retrieving token ...
Token: QQUq08yl1EXncOQXT6Mzr3DIQ-UzwVi3z__iwtKYUs7hHQsd_zQp7CGE7NbQSYHXsM2uJw.
GSFId: 3a719a14a3970433
Using token to connect to API
1 / 1 it.android.demi.elettronica.pro
Error while downloading it.android.demi.elettronica.pro : 'App not purchased'
A few packages could not be downloaded :
it.android.demi.elettronica.pro
'App not purchased'
```

**Comment by matlink** [comment]
Be sure to get the correct `gplaycli.conf` using `-c /etc/gplaycli/gplaycli.conf`

**Comment by BiatuAutMiahn** [comment]
bug=resolved, i ended up just linking the /etc config to ~/.config, and presto. thanks for ur help

**Comment by BiatuAutMiahn** [comment]
However with commit 1888c60:
```
GPlayCli version 3.0 [Python2.7.12+] 
Configuration file is /home/biatu/.config/gplaycli/gplaycli.conf
Using cached token.
Using token to connect to API
1 / 1 it.android.demi.elettronica.pro
Error while downloading it.android.demi.elettronica.pro : 'App not purchased'
A few packages could not be downloaded :
it.android.demi.elettronica.pro
'App not purchased'
```

cat ~/.config/gplaycli/gplaycli.conf
```
[Credentials]
gmail_password=****BK0v
android_ID=************c725
gmail_address=****@gmail.com
language=en_US
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=~/.cache/gplaycli/token

```

**Comment by matlink** [comment]
switch token=False in the config file
