### ISSUE TITLE
Error: download() got an unexpected keyword argument 'progress_bar'

### ISSUE THREAD

**Issue by ford--prefect** [matlink/gplaycli#112]
With version 3.1 on Archlinux (used with python 2.7, installed via setup.py) I get the following error for all apps ready to be downloaded:

Error while downloading de.schildbach.oeffi : download() got an unexpected keyword argument 'progress_bar'

Thankyou for developing this software!

**Comment by olebowle** [comment]
I had the same issue. You need to package a newer version of python2-gpapi. I used the latest commit.

**Comment by matlink** [comment]
0.1.5 has just been pushed to pypi, you can install it.
I'll need to update gplaycli to fetch the 0.1.5 version.

**Comment by matlink** [comment]
Version 3.2 of `Gplaycli` using `gpapi >= 0.1.5` has been pushed to pypi.
Please close if resolved.

**Comment by ford--prefect** [comment]
With gplaycli 3.2 and gpapi 0.1.5 it works for me.
