### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#115]
For better code maintenance, I will remove Python 2 support since the Python 3 version is now working great. 
Is there any reason not to do it now?

**Comment by NoMore201** [comment]
Python 2 has a bad unicode string support. Sometimes it throws errors about unicode encoding, especially when fetching reviews. I guess +1 reason to switch to Python 3.

**Comment by NoMore201** [comment]
Here is an example:

https://travis-ci.org/NoMore201/googleplay-api/builds/289117733

**Comment by matlink** [comment]
Fixed since 139cfbc38ba52d45e84b834c48194c503c96e9d7
