### ISSUE TITLE
TypeError: login() got an unexpected keyword argument 'device_codename'

### ISSUE THREAD

**Issue by msdos** [matlink/gplaycli#116]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [X] Operating System (ie Ubuntu 16.04)
Ubuntu 16.04
- [X] Python version when running `gplaycli` (should be 2.7 for now)
2.7.11
- [X] GPlayCli version via `gplaycli -v`
3.3
- [X] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
pip install gplaycli
- [X] The authentication method: (own) credentials or (own) token.
Using provided conf in https://github.com/matlink/gplaycli/blob/af12426a5059d7a7e8058dd0286cc11ef59983cb/gplaycli.conf

Just by running `gplaycli -v` I got:

```
GPlayCli version 3.3 [Python2.7.11] 
Configuration file is /etc/gplaycli/gplaycli.conf
Using cached token.
Using token to connect to API
Traceback (most recent call last):
  File "bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "lib/python2.7/site-packages/gplaycli/gplaycli.py", line 543, in main
    success, error = cli.connect_to_googleplay_api()
  File "lib/python2.7/site-packages/gplaycli/gplaycli.py", line 193, in connect_to_googleplay_api
    api.login(authSubToken=self.token, gsfId=int(self.gsfid,16), device_codename=self.device_codename)
TypeError: login() got an unexpected keyword argument 'device_codename'
```

**Comment by matlink** [comment]
See https://github.com/matlink/gplaycli/releases/tag/3.4
Update using `pip install gplaycli --upgrade` please

**Comment by msdos** [comment]
Don't forget to add `pyaxmlparser`  as a dependency, I had to install it by hand.

```
from pyaxmlparser import APK  # Pyaxmlparser
ImportError: No module named pyaxmlparser
```

Had to delete `rm ~/.cache/gplaycli/token` as well after upgrading to get rid of 

```
google/protobuf/internal/python_message.py", line 1072, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
```

Now everything is working as expected, and downloading packages unavailable in the past (like Dropbox) is now possible! Thanks for the good work!

**Comment by matlink** [comment]
normally of you use Python 2 there is no need for pyaxmlparser (it is python3 only).
