### ISSUE TITLE
Error in search result

### ISSUE THREAD

**Issue by muzzyrost** [matlink/gplaycli#117]
$ gplaycli -s youtube -v
GPlayCli version 3.4 [Python2.7.12] 
Configuration file is gplaycli/gplaycli.conf
Using credentials to connect to API
Using plaintext password
Title                                              Creator                                             Size    Downloads                 Last Update   AppID                                    Version     Rating  
YouTube                                            Google LLC                                          26.6MB  1,000,000,000+ downloads  Oct 10, 2017  com.google.android.youtube               1239603300  4.27    
YouTube Studio                                     Google LLC                                          10.4MB  10,000,000+ downloads     Sep 7, 2017   com.google.android.apps.youtube.creator  117343038   4.25    
Free music for YouTube: Stream                     MWM - Best free music and audio apps for Android    6.8MB   10,000,000+ downloads     Aug 29, 2017  com.djit.apps.stream                     10020400    4.47    
Kids videos for YouTube                            work4mob                                            6.0MB   1,000,000+ downloads      Sep 27, 2017  com.tubekids                             23          3.99    
Free Music Player for YouTube: Endless Free Songs  Free Music: Endless Songs: Download Free AT Player  3.6MB   5,000,000+ downloads      Oct 11, 2017  com.atpc                                 176         4.43    
Google Play Music                                  Google LLC                                          16.5MB  1,000,000,000+ downloads  Aug 31, 2017  com.google.android.music                 52181       3.93    
Traceback (most recent call last):
  File "/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/lib/python2.7/site-packages/gplaycli/gplaycli.py", line 549, in main
    cli.search(list(), args.search_string, nb_results, not args.paid)
  File "/python2.7/site-packages/gplaycli/gplaycli.py", line 416, in search
    enumerate(result)))
  File "/python2.7/site-packages/gplaycli/gplaycli.py", line 415, in <genexpr>
    print("".join(str("%s" % item).strip().ljust(col_width[indice]) for indice, item in
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 19: ordinal not in range(128)

**Comment by matlink** [comment]
Yeah, python2+3 Unicode support is such a mess ...
Any way I won't support python2 anymore, please try the python3 version if you can.
`pip3 install gplaycli --upgrade`

**Comment by muzzyrost** [comment]
Thanks, close issue plz.
