### ISSUE TITLE
Error: The 'distribute' distribution was not found and is required by androguard

### ISSUE THREAD

**Issue by ford--prefect** [matlink/gplaycli#118]
Hi,

since the upgrade to gplaycli 3.4 (EDIT: changed from 3.3 to 3.4, was incorrect before), I and others experience the following error. The setup is Archlinux with python2.7, gplaycli installed via AUR (which uses the setup.py method).
The error is the following:
`Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'distribute' distribution was not found and is required by androguard`
At first look this looks like the 'androguard' module misses the module 'distribute', which is strange for several reasons:
• the distribute module was last updated 2013 and does nothing but installing setuptools, which are installed before building the package
• the androguard package did not change recently, this error comes reproducibly with the upgrade of gplaycli 3.2 -> 3.3

If you need more info I'll happily provide.

**Comment by matlink** [comment]
I thin commit 2a3e8f58b16651cc7452dafc0788a074b14bbcd5 introduced the bug. can you confirm by running the version before that commit?

**Comment by ford--prefect** [comment]
I can confirm that 6b6da64 works but 2a3e8f5 doesnt. Thanks for the very precise catch!

**Comment by matlink** [comment]
Okay so `androguard` is still using `Distutils` which is deprecated.
I suggest you to use the python3 version of gplaycli if you can, since it uses `pyaxmlparser` instead of `androguard`.
Any way, in a near future Python2 won't be supported any more due to the pain to maintain both 2 and 3 versions.
