### ISSUE TITLE
Unusable. It keep giving me "IndexError: list index out of range" error.

### ISSUE THREAD

**Issue by psycholyzern** [matlink/gplaycli#120]
- [ 16.04 ] Operating System (ie Ubuntu 16.04)
- [ 2.7 and 3.5 ] Python version when running `gplaycli` (should be 2.7 for now)
- [ 3.4 ] GPlayCli version via `gplaycli -v`
- [ `git clone`, `pip install --user gplaycli`, ` python setup.py install`, `./gplaycli/gplaycli.py` ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ token (mine and yours) ] The authentication method: (own) credentials or (own) token.  
  
I was running an old version (can't remember the version) and decided to update to the latest. But after I installed, I got this error:
```
myuser@lost:~$ gplaycli -v
GPlayCli version 3.4 [Python2.7.12]
Configuration file is /home/myuser/.config/gplaycli/gplaycli.conf
Using cached token.
Using token to connect to API
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.4', 'console_scripts', 'gplaycli')()
  File "build/bdist.linux-x86_64/egg/gplaycli/gplaycli.py", line 543, in main
  File "build/bdist.linux-x86_64/egg/gplaycli/gplaycli.py", line 193, in connect_to_googleplay_api
  File "/home/myuser/.local/lib/python2.7/site-packages/gpapi/googleplay.py", line 200, in login
    self.search('firefox', 1, None)
  File "/home/myuser/.local/lib/python2.7/site-packages/gpapi/googleplay.py", line 285, in search
    cluster = response.payload.listResponse.cluster[0]
IndexError: list index out of range
```
I installed Gplaycli with every way that were stated except via `apt`. Tried with python2.7 and python 3.5.. I even reinstalled both pip2 and pip3. Now I gave up because haven't getting any progress. I also already tried the orginal token-dispenser and the one you forked. Both giving the same error.
  
Also I saw you are using `https://matlink.fr/token/email/gsfid`. But when I put `gsfid` path on my token-dispenser server, it said `No password for this email`. But putting email (`https://myserver/token/email/myemail@gmail`) produce token.  
I don't know what is the real issue here. It has been more than an hour since I started to upgrade.
Thanks

**Comment by matlink** [comment]
I think your IP address is temporary banned by Google servers. It happened to me once.

**Comment by psycholyzern** [comment]
Oh. I will give it a try on another server.  
Btw, my 2nd part of question, I saw you were using ` https://matlink.fr/token/email/gsfid` for token inside gplaycli.conf. But back then, you were using email instead of `gsfid`. I tried putting `gsfid` on y url but it said `No password for this email`. Which one is the correct and should I use for the latest version?

**Comment by matlink** [comment]
See #114

**Comment by psycholyzern** [comment]
Okay thanks. Seems that you were right. I tested on another server and it works normally.
