### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by abhijeet0007** [matlink/gplaycli#124]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kJL7TB-build/

Please provide those informations:

- [Ubuntu 16.04 ] Operating System (ie Ubuntu 16.04)
- [ tried all the method] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [x] The authentication method: (own) credentials or (own) token.
- [Python 2.7.12] Python version when running `gplaycli` (should be 2.7 for now)
- [x] GPlayCli version via `gplaycli -v`

**Comment by matlink** [comment]
Give more info

**Comment by abhijeet0007** [comment]
pip install gplaycli
Collecting gplaycli
  Using cached GPlayCli-3.10.tar.gz
    Complete output from command python setup.py egg_info:

        Python2 support has been removed since version 3.9
        Please install GPlayCli with Python3
        Or install version 3.8 but don't expect support

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TpmkOj/gplaycli/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
