### ISSUE TITLE
Feature request: use named logger and use logger to log error messages when printing them

### ISSUE THREAD

**Issue by nicktogo** [matlink/gplaycli#125]
Currently gplaycli does use logging module to log some messages but I saw from the code that it is using the root level logger. And when there is an error raised, gplaycli just print the error messages to STDOUT instead of logging them. 

I am trying to import gplaycli in my code and I find that it would be better if gplaycli used named logger (i.e. use `logging.getLogger(__name__)`) instead of configuring root level logger. Doing such thing can give developers like me more flexibilities to manage the both logs from gplaycli and our own code.
Also, using logger to log error messages beside printing them to STDOUT can also give us a chance to gather error messages from gplaycli.

Thank you very much for developing such great library.

**Comment by matlink** [comment]
Thanks for your precise report.
I'll do it soon. If you want to PR feel free to do so.

**Comment by nicktogo** [comment]
@matlink Hi, may I ask current development progress for this issue? If you haven't had time to do this, I can open a PR in the next couple of days.

**Comment by matlink** [comment]
Well PR then I didn't have time sorry :(

**Comment by matlink** [comment]
Implemented in 25a356f7302abd54e3c9ce1e244c9e0ef783475d
