### ISSUE TITLE
Error processing purchase [DF-BPA-30]

### ISSUE THREAD

**Issue by lambdacrash** [matlink/gplaycli#129]
- [Ubuntu 16.04.3 LTS] Operating System (ie Ubuntu 16.04)
- [Python3.5.2] Python version when running `gplaycli` (should be 2.7 for now)
- [3.10] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli] The way you installed [...]
- [token] The authentication method: (own) credentials or (own) token.

I experienced the following issue while downloading a free app:
```
$ gplaycli -v -pd com.BuffaloGrill -f /tmp/
[INFO] GPlayCli version 3.10 [Python3.5.3] 
[INFO] Configuration file is /home/xxxxxxx/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using token to connect to API
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
[INFO] Token: YwXaM3jaH7N[...]FGl1wHdy8Gw.
[INFO] GSFId: 365[...]f
[INFO] 1 / 1 com.BuffaloGrill
Error while downloading com.BuffaloGrill : 'Error processing purchase. [DF-BPA-30]'
A few packages could not be downloaded :
com.BuffaloGrill
'Error processing purchase. [DF-BPA-30]'
```

**Comment by NoMore201** [comment]
Fetching details for that app I get this
```
{'docId': 'com.BuffaloGrill',
'title': 'Buffalo Grill',
'author': 'Mobistep',
'versionCode': 0,
[..] }
```
it could be related to this https://github.com/NoMore201/playmaker/issues/8 (problem is related to gpapi though).

Basically there are some apps returning `versionCode = 0`, and I still don't know what is the problem with those apps, tried also changing locale/timezone and devices. Apps giving this problem so far are:

- `com.BuffaloGrill`
- `it.telecomitalia.centoottantasette`
- `de.schildbach.oeffi`

**Comment by NoMore201** [comment]
Moreover, I just noticed that these apps can be succesfully downloaded with YalpStore, so it could be a problem with gpapi implementation

**Comment by lambdacrash** [comment]
Thank you @NoMore201. 
I noticed that if I retry the same command (with the same appID) few seconds after a failure, I am able to download the application. But, this behavior is not 100% reproducible. Sometimes, 1 retry is enough, sometimes 25 retries fail :/

**Comment by matlink** [comment]
Well sometimes when you download a lot of app, Google temporarily blocks your IP. That could be another problem on top of this one.

**Comment by lambdacrash** [comment]
Thank you @matlink.
This error can occur even if I did not download application for several hours :S

**Comment by NoMore201** [comment]
I did some other tests, using this procedure

- Go to google account settings -> Sign-in & security
- Go to recenlty used device
- Remove the device registered by gpapi/gplaycli
- In gpapi, inside `device.properties` under the `bacon` section, modify SimOperator and CellOperator with values from my phone (italian provider)

Now i'm able to download `it.telecomitalia.centoottantasette` (which you might guess is the android app of my phone provider). I guess some apps have restriction based on these values, and the problem isn't alway the ip block

**Comment by lambdacrash** [comment]
Thank you @NoMore201 
I'll try it and let you know!

**Comment by matlink** [comment]
Close since no news. Ask to re-open if I'm wrong.
