### ISSUE TITLE
download() got an unexpected keyword argument 'expansion_files'

### ISSUE THREAD

**Issue by alter-al** [matlink/gplaycli#131]
When I tried to download apk from store, I was getting error:
    download() got an unexpected keyword argument 'expansion_files'

- [Mac Sierra 10.12.6] Operating System
- [Python3.6.2] Python version when running `gplaycli`
- [GPlayCli version 3.10 ] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli] The way you installed `gplaycli`
- [gplaycli.conf] The authentication method

LOG:
    `gplaycli -v -pd com.ubercab
    [INFO] GPlayCli version 3.10 [Python3.6.2]
    [INFO] Configuration file is ~/.config/gplaycli/gplaycli.conf
    [INFO] Retrieving token ...
    [INFO] Token: <my_tocken>.
    [INFO] GSFId: <my_GSFId>
    [INFO] Using token to connect to API
    [INFO] 1 / 1 com.ubercab
    Error while downloading com.ubercab : download() got an unexpected keyword argument 'expansion_files'
    A few packages could not be downloaded :
    com.ubercab
    download() got an unexpected keyword argument 'expansion_files'`

**Comment by matlink** [comment]
Which gpapi version do you have?

**Comment by alter-al** [comment]
gpapi@4.3.1

**Comment by matlink** [comment]
gpapi has no such version, how did you install it ?
