### ISSUE TITLE
Cannot download a few apps

### ISSUE THREAD

**Issue by jr3074** [matlink/gplaycli#132]
Cannot download a few apps (snapchat com.snapchat.android and BeautyPlus com.commsource.beautyplus). But download the others app and game works perfectly.
Can you download them with this app? I also try to use racoon but i cannot download them.
I tried to use my real gsf-id and also create new gsf-id, i use my own token and also tried @matlink token.
All of them, i cannot download the apps. 
Maybe google will update again?
Can you download them with this app?

Operating System Debian 8
[Python3.6.2] Python version when running gplaycli
[GPlayCli version 3.10 ] GPlayCli version via gplaycli -v
[pip3 install gplaycli] The way you installed gplaycli
[gplaycli.conf] The authentication method

**Comment by matlink** [comment]
Please try with another android device (using -dc option)

**Comment by trungducng** [comment]
this issue still appear in some case when I have tried to change the -dc.

**Comment by matlink** [comment]
I am able to download snapchat with default settings.
