### ISSUE TITLE
 [Errno 110] Connection timed out'

### ISSUE THREAD

**Issue by trungducng** [matlink/gplaycli#135]
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='matlink.fr', port=443): Max retries exceeded with url: /token/email/gsfid (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff3f712f6d8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

- [ ] Operating System (Ubuntu 16.04)
- [ ] Python version when running `gplaycli`: 3.5.2
- [ ] GPlayCli version via `gplaycli -V`: 3.10
- [ ] The way you installed `gplaycli`: `pip3 install gplaycli`
- [ ] The authentication method: (own) credentials

I don't know why when I'm trying to do any task by gplaycli, it returns this errors. I guess the reason is involve in the server: matlink.fr when I don't have ability to connect to it in my pc

**Comment by matlink** [comment]
Can you try `telnet matlink.fr 443` ?

**Comment by trungducng** [comment]
@matlink I tried and it returned ‘Connection timeout’
Besides, I tried to connect it via my browser and it could not connect. 
Should I fake ip to connect

**Comment by matlink** [comment]
No, but something is blocking the connection (a firewall).
