### ISSUE TITLE
Error retrieving information from server. [DF-DFERH-01]

### ISSUE THREAD

**Issue by TheT3ngu** [matlink/gplaycli#137]
Hey guys,
since a week or so I am not able to update my APKs anymore. Searching for Apps (gplaycli -s ...) and downloading Apps (gplaycli -d ...) works flawlessly, but whenever I try to update all Apps in a given folder, gplaycli says (after promting which Apps are going to be updatet): `Error retrieving information from server. [DF-DFERH-01]`.

System Information: 
```
[INFO] GPlayCli version 3.9 [Python3.5.2] 
[INFO] Configuration file is /home/tengu/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using token to connect to API
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
[INFO] Token: bAV4rB7WnngPJ8jGbJrjYZmpxqBFPBTNVadAWtB0M0AL591zbwFbbQ2oTgb6hYKgE7T3pA.
[INFO] GSFId: 3ae9ba1a8709a927
```

On Ubuntu 16.04 Server, installed via pip, own creds, public token.

Thanks for any hint!

edit: I get the `[INFO] Token has expired or is invalid. Retrieving a new one...` message everytime I `gplaycli -v`, is that normal?

**Comment by TheT3ngu** [comment]
I noticed that I was not on the last version available, so I updatet to version 3.10. But it didn't fixed the Problem, just altered the error code. Whenever I try to update my folder with APKs I now get this:

```
/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py:264: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  message = googleplay_pb2.ResponseWrapper.FromString(response.content)
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 511, in main
    cli.prepare_analyse_apks()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 213, in prepare_analyse_apks
    self.prepare_download_updates)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 231, in analyse_local_apks
    store_version_code = detail['versionCode']
TypeError: 'NoneType' object is not subscriptable
```

Output of `gplaycli -v`: 
```
[INFO] GPlayCli version 3.10 [Python3.5.2] 
[INFO] Configuration file is /home/tengu/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using token to connect to API
/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py:264: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  message = googleplay_pb2.ResponseWrapper.FromString(response.content)
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
[INFO] Token: bgWKUI7bh0sjYhe99O5ac-5RQ2mFxSwBKRsrbe1s6IKGya296LZmZkKxUd21U2gWud490w.
[INFO] GSFId: 3b4fb494e7ad4ef4
```

Still on Ubuntu 16.04 Server, installed via pip, own creds, public token.

**Comment by TheT3ngu** [comment]
Thanks for the hint, I manually checked all APKs and in fact it was the Amazon-App. I switched it with the new one and now the "NoneType"-Error is gone.
But I still get the DF-DFERH-01 error from time to time, any hint fot this one too?

**Comment by matlink** [comment]
I'll need more precise informations. Like the package name of the amazon-app and the exact command you're running.

**Comment by matlink** [comment]
Lack of infos.

**Comment by 7heaven** [comment]
@TheT3ngu delete file "token" located in ~/.cache/gplaycli/ and try again

**Comment by realityexists** [comment]
> @TheT3ngu delete file "token" located in ~/.cache/gplaycli/ and try again

This worked for me, thanks a lot! I got this when trying to download any APK (`gplaycli -d ANYTHING`) where ANYTHING doesn't even have to be a valid package name. Can this issue be re-opened @matlink ? I upload the old token file if that would help

**Comment by realityexists** [comment]
`gplaycli -d x` reproduced it

**Comment by muzzyrost** [comment]
> I still need the command you're running at least to try to reproduce.

You need just made about 10 downloads to reproduce bug.

**Comment by realityexists** [comment]
Still happens. I deleted the token file again and it worked... eventually, but I got "Malformed request" many times.

```
gplaycli.exe -v -d some.app
[INFO] GPlayCli version 3.25 [Python3.6.8]
[INFO] Configuration file is C:\Users\USERNAME/.config/gplaycli/gplaycli.conf
[INFO] Device is bacon
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token/email/gsfid/bacon
[ERROR] Unknowned error: Malformed request
```

**Comment by detrout** [comment]
I'm getting the DH-DFERH-01 error now.
```
python3 -m gplaycli.gplaycli -d com.zwift.zwiftgame -f .
[ERROR] Error while downloading com.zwift.zwiftgame : 'Error while retrieving information from server. [DF-DFERH-01]'
[ERROR] A few packages could not be downloaded :
com.zwift.zwiftgame
'Error while retrieving information from server. [DF-DFERH-01]'
```
```
git rev-parse HEAD
4af7d3d6a991de4d4c69bbf09d26ea6554f880d1
```

Also get the same error for com.lego.mindstorms.ev3programmer
