### ISSUE TITLE
Credentials in system-wide directory

### ISSUE THREAD

**Issue by DamienCassou** [matlink/gplaycli#14]
The credentials are stored in `/etc` which make them non modifiable by users

**Comment by matlink** [comment]
`--config` is made for that, I think.

**Comment by almet** [comment]
The problem I see is that it blocks the installation with a pip inside a virtualenv, since the data files are tried to be installed dierctly in `/etc/`. This should be done only in the debian installer and not in the setup.py.

**Comment by matlink** [comment]
This is true. Is it easy to do ?

Le 2 décembre 2015 21:06:49 GMT+01:00, Alexis Metaireau <notifications@github.com> a écrit :
>The problem I see is that it blocks the installation with a pip inside
>a virtualenv, since the data files are tried to be installed dierctly
>in `/etc/`. This should be done only in the debian installer and not in
>the setup.py.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/14#issuecomment-161417737

-- 
Matlink - sysadmin Matlink.fr

**Comment by raphael0202** [comment]
Couldn't the config file be in ~/.config/gplaycli? Credentials should be user-dependent, and ~/.config is the preferred folder to store config files.
And no need to have root privileges.

**Comment by DamienCassou** [comment]
@raphael0202 I agree with you.

**Comment by matlink** [comment]
Yes I could add that folder to override /etc if there is a credentials.conf in it.

**Comment by matlink** [comment]
Fixed by 20f65ca91820018fe3f1a076238ec7293ceada9b , re-open if not.

**Comment by almet** [comment]
Thanks!
