### ISSUE TITLE
How long will the token last for?

### ISSUE THREAD

**Issue by nicktogo** [matlink/gplaycli#145]
Hi, 
As my working experience with gplaycli, I found that the token expired shortly, only last for one or two minutes. However, from the original token dispenser repo, under this issue, [yeriomin/token-dispenser/issues/12#issuecomment-335564226](https://github.com/yeriomin/token-dispenser/issues/12#issuecomment-335564226), its developer said the token will valid for months. So I am curious about this situation on gplaycli. Is there a reason why token will expire shortly?
I used default gplaycli.conf and token dispenser comes with this configuration file.

**Comment by matlink** [comment]
It seems to have changed recently.

**Comment by matlink** [comment]
https://github.com/NoMore201/googleplay-api/issues/18
