### ISSUE TITLE
Add argument to add random delays before downloading with -F (list)

### ISSUE THREAD

**Issue by enovella** [matlink/gplaycli#146]
Hi,

it seems that when crawling APKs from a big list, after around 50~70 APKs the servers refuses you to continue downloading.

Would it be possible to add an argument that it could avoid this behaviour by adding random timing between downloads?

Cheers

**Comment by matlink** [comment]
What should be the range of the random wait?
1-10 seconds or more?

**Comment by enovella** [comment]
Sort of. Although an argument to specify maximum could be a good option.

**Comment by enovella** [comment]
FYI, v3.17 seems to work very stable and you can download many more APKs in one go.
