### ISSUE TITLE
ImportError: cannot import name 'DerBitString'

### ISSUE THREAD

**Issue by deounix** [matlink/gplaycli#147]
Operating System: CentOS 7.4
Python version: 3.4
GPlayCli version: 3.12
The way you installed `gplaycli`: pip3 install gplaycli
The authentication method: token (default)

Error:

    from Crypto.PublicKey import RSA
  File "/root/tutorial_env/lib64/python3.4/site-packages/Crypto/PublicKey/__init__.py", line 21, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
ImportError: cannot import name 'DerBitString'

**Comment by matlink** [comment]
Could you please try in a new virtualenv? It seems related to your virtualenv.

**Comment by dengshilong** [comment]
Maybe you install both PyCrypto and PyCryptodome, it may cause conflict.

**Comment by banjin** [comment]
pip uninstall PyCrypto
pip uninstall PyCryptodome
pip install PyCryptodome
