### ISSUE TITLE
Just -h and -V works when calling script from PHP  

### ISSUE THREAD

**Issue by teacherlove** [matlink/gplaycli#154]
Hello .
I am testing script by PHP  , when i call gplaycli directly from command line it works fine .

But when calling it from PHP script only -h and -V command works. it seems seconds arguments does not work  . for example

shell_exec('gplaycli -v');  works  
shell_exec('gplaycli -d com.whatsapp'); does now work .

Any comment ?
By the way i use another python script ( youtube-dl ) by several arguments and it works fine .

Python 3.6.3 - PHP 5.6

**Comment by NoMore201** [comment]
1. Specify apk name with quotes `'gplaycli -d "com.whatsapp"'`
2. Try calling gplaycli module from python `'python -m gplaycli -d "com.whatsapp"'`
and see what happens

**Comment by matlink** [comment]
"Doesn't work" is not an issue. How doesn't it work? Is there an error? Does something happen or not?
