### ISSUE TITLE
Slow speed on large cache downloading

### ISSUE THREAD

**Issue by muzzyrost** [matlink/gplaycli#156]
Hi, downloading speed on large obb files very slow. And it slower when file is bigger. You can see speed slowdown after dowbloading first 100-200 MB. Tested on different ubuntu machines. On Raccon Apk downloader I didn't see same issue.

**Comment by matlink** [comment]
Hum, it should be related to the fact that gplaycli & gpapi stores everything in memory before writing down to the disk. I'm gonna investigate it.

**Comment by muzzyrost** [comment]
Thanks!

**Comment by matlink** [comment]
Which APK triggers this issue? (give an example that I can try)

**Comment by muzzyrost** [comment]
com.pixel.gun3d
com.superevilmegacorp.game

Wait for downloading first 200 MB of obb file and then check speed again.
