### ISSUE TITLE
OSError: No configuration file found at ['gplaycli.conf'

### ISSUE THREAD

**Issue by schniggie** [matlink/gplaycli#157]
Just installed the latest version with pip3 and get the following error:

gplaycli -s com.bankid.bus
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/gplaycli.py", line 640, in main
    cli = GPlaycli(args, args.config)
  File "/usr/local/lib/python3.6/dist-packages/gplaycli/gplaycli.py", line 89, in __init__
    raise OSError("No configuration file found at %s" % cred_paths_list)
OSError: No configuration file found at ['gplaycli.conf', '/root/.config/gplaycli/gplaycli.conf', '/etc/gplaycli/gplaycli.conf']

I am using Kali 2 rolling. Used it long time in an older version with python 2 and it worked perfect. My python version is Python 3.6.4rc1.

**Comment by matlink** [comment]
Yes, that's expected. You need to manually download `gplaycli.conf` from the github repo and put it either in `/root/.config/gplaycli/` or in `/etc/gplaycli/`
