### ISSUE TITLE
How to download apks for older Android SDK versions?

### ISSUE THREAD

**Issue by lgommans** [matlink/gplaycli#158]
My Android is pretty old and some downloads don't work for my SDK version. How can I specify it? I'm pretty sure the app is still released for my device version, and on the Play website it says the version is different per device so that seems to confirm it.

When installing the downloaded version via adb, I get the message `INSTALL_FAILED_OLDER_SDK`. There seems to be no command line option for it, though some are undocumented: e.g. in `-g`, what's a GSF ID? And how would I obtain a token which needs to be supplied at the same time? And what's the device codename for, could that help the store understand I need an older version? The default text (bacon) seems bogus. Perhaps one of these options could help me, but reading the source to see how those options are used, doesn't tell me anything, and the help text doesn't explain what they are for or how I would obtain such tokens/IDs/codenames.

- Operating System: Debian Stretch
- Python version when running `gplaycli`: 3.5.3
- GPlayCli version via `gplaycli -v`: "GPlayCli version unknown: gplaycli not installed (version in setup.py)" in `setup.py`: "version='3.19'"
- The way you installed `gplaycli`: `git clone` and just run it (with modifications to imports so it finds `util` and `hooks`, and dependencies via sudo pip3 install)
- The authentication method: I've tried own credentials and the default token

**Comment by matlink** [comment]
Do you have the codename of you phone?
Do you know the SDK version of your phone?
I think there is a way with the API that gplaycli is using to tell to use an older SDK version. These informations are stated in https://github.com/NoMore201/googleplay-api/blob/master/gpapi/device.properties . For example the 'angler' phone is using the SDK 27. So I guess if you manually change the SDK number in the section corresponding to your phone, you could achieve what you want to do.

**Comment by lgommans** [comment]
That worked!

Earlier I already tried adding `headers['User-Agent'] = headers['User-Agent'].replace('sdk=25,', 'sdk=19')` in the `getDefaultHeaders` method of `googleplay.py`, but that didn't work. If I change the API_INT of the default device instead, I get a different APK which installs fine. I guess the `getDefaultHeaders` method is not used for the actual download call, but I couldn't figure out where it took the SDK version from so I couldn't fix that. Thank you for pointing it out to me :)

**Comment by matlink** [comment]
I don't know if it's a typo or what, but you wrote `replace('sdk=25,', 'sdk=19')` and there is a `,` in addition after the `25`. But you were wrong, the `gpapi` is using `getDefaultHeaders` and you seem to have make a mistake somewhere.
There easiest solution is indeed to edit the `device.properties`. I think it could be interesting in future versions to have a cmd line argument to point to a custom one (not to change the default one).
FYI, you can add a section in `device.properties` by coping the `bacon` one, putting the name you want and replacing the `API_INT` by `19`.

**Comment by lgommans** [comment]
> there is a `,` in addition after the `25`

Oh dang! I put it in `sdk=25,` on purpose (including the field separator often prevents accidental other replacements), but then of course I had to include it in the replacement value as well!

> I think it could be interesting in future versions to have a cmd line argument to point to a custom one (not to change the default one).

That could be useful indeed, though for me (unless someone else is also interested in using this), the current solution is also fine :)
