### ISSUE TITLE
could not download HTC apk com.htc.screencapture

### ISSUE THREAD

**Issue by snsnsjsn** [matlink/gplaycli#159]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [x] Operating System (ie Ubuntu 16.04)
[root@numbone gplaycli]# lsb_release -a
LSB Version:	:base-4.0-ia32:base-4.0-noarch:core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.8 (Final)
Release:	6.8
Codename:	Final
[root@numbone gplaycli]# 

- [ ] Python version when running `gplaycli` (should be 2.7 for now)
Python 2.7.8
- [ ] GPlayCli version via `gplaycli -v`
[INFO] GPlayCli version 3.19 [Python3.4.5] 
[INFO] Configuration file is gplaycli.conf
[INFO] Using cached token.
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
git clone https://github.com/matlink/gplaycli && pip3 install ./gplaycli/

- [ ] The authentication method: (own) credentials or (own) token.
use deafult 

information
Error while downloading com.htc.screencapture : 'Error while retrieving information from server. [DF-DLA-26]'
A few packages could not be downloaded :
com.htc.screencapture
'Error while retrieving information from server. [DF-DLA-26]'

![image](https://user-images.githubusercontent.com/11435527/35914027-bb8289b0-0c3c-11e8-94cb-3a19ab33353f.png)

**Comment by vitsum** [comment]
Same with these apps:
"com.asus.email","com.sec.android.app.music","com.keesing.android.puzzleplayer.app.nl","com.sec.android.app.kidshome","de.schroedel.cas","com.blackberry.exfat","com.gamaxgamesidc.ClashofGangsterKillerMafia","com.samsung.android.videolist","tv.arte.plus7.leanback","de.cyberdream.dvbc.tv.player","air.com.befunky.BeFunkyPad","com.sukros.timelapse","com.yotadevices.yotaphone2.checkers","com.sec.android.app.launcher","com.servesilicon.wordmaker","com.sonyericsson.textinput.uxp","com.dosomever.hackeightballpool","com.asus.themes.candygirl","kr.kbw.skin","lex.com.webbrowser","com.cloudmosa.puffinTV","com.mysms.android.tablet","com.htc.sense.mms","com.sonymobile.areffect.birthday_theme","com.sonymobile.areffect.circus_theme","com.resolutiongames.wonderglade","com.minditorium.tjuhej.daydream","air.com.flowplay.ourWorld","net.matsudamper.smalltweet","com.blankmediagames.townofsalem","net.roll20.playerappandroid","com.com2us.acefishing.vr.freefull.google.global.android.common"


What does this error mean?

**Comment by trungducng** [comment]
Seem that all these package is based on the specific device. For ex: "com.asus.email" can only be downloaded by asus device (like: asus zenfone 2)
=> need to use correctly device (I mean GSFID) to download the special apps

**Comment by snsnsjsn** [comment]
maybe for the network not good,
 
try 3 times it is ok now , like this downloading the evernote

[root@numbone down]# gplaycli -d "com.evernote"
Error while downloading com.evernote : 'Error while retrieving information from server. [DF-DLA-26]'
A few packages could not be downloaded :
com.evernote
'Error while retrieving information from server. [DF-DLA-26]'

[root@numbone down]# gplaycli -d "com.evernote"
Error while downloading com.evernote : 'Error while retrieving information from server. [DF-DLA-26]'
A few packages could not be downloaded :
com.evernote
'Error while retrieving information from server. [DF-DLA-26]'

[root@numbone down]# ^C
[root@numbone down]# gplaycli -d "com.evernote"
[################################] 31260672/31264122 - 00:00:00

so , if anybody encount the same problem ,could try more times.
