### ISSUE TITLE
BadAuthentication

### ISSUE THREAD

**Issue by wonkydonky** [matlink/gplaycli#162]
System (ie Ubuntu 16.04) Debian stable
- [x] Python version when running `gplaycli` (should be 3+)  2.7.13
- [x] GPlayCli version via `gplaycli -v`  0.2.1
- [x] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...  Debian repositories
- [x] The authentication method: (own) credentials or (own) token. Token using [default settings](https://github.com/matlink/gplaycli/blob/master/gplaycli.conf)

When I type `gplaycli -s search_string -c gplaycli.conf` I always get this:

    Using credentials.conf from current directory...
    Cannot login to GooglePlay ( server says: BadAuthentication )

I don't have a gmail/google account. Do I need one to use gplaycli? Or an "andoid id"? Or should I be able to download the apk without a gmail account? What am I doing wrong?

Thanks.

**Comment by matlink** [comment]
Please upgrade `gplaycli` to version 3.19 and then retry.

**Comment by matlink** [comment]
Do `gplaycli` instead of `./gplaycli`.

**Comment by wonkydonky** [comment]
No luck.

    $ virtualenv gplaycli; cd gplaycli; source bin/activate
    $ git clone https://github.com/matlink/gplaycli && pip3 install ./gplaycli/
    [...]
    Installing collected packages: six, setuptools, protobuf, pycryptodome, chardet,
    idna, certifi, urllib3, requests, gpapi, lxml, pyaxmlparser, args, clint, GPlayCli
    Running setup.py install for GPlayCli ... done
    Successfully installed GPlayCli-3.19 args-0.1.0 certifi-2018.1.18 chardet-3.0.4 clint-0.5.1
    gpapi-0.4.2 idna-2.6 lxml-4.1.1 protobuf-3.5.1 pyaxmlparser-0.3.7 pycryptodome-3.4.11
    requests-2.18.4 setuptools-38.5.1 six-1.11.0 urllib3-1.22
    $ gplaycli
    bash: gplaycli: command not found

**Comment by wonkydonky** [comment]
OK it seems to work now, I had to use `virtualenv -p python3` because Debian is defaulting to Python 2.7. Please add this to the README. Thanks.
