### ISSUE TITLE
No .cache directory on OSX

### ISSUE THREAD

**Issue by ssaenz11** [matlink/gplaycli#166]
![captura de pantalla 2018-03-01 a las 11 36 12 a m](https://user-images.githubusercontent.com/30849540/36856980-5924b90e-1d45-11e8-95ea-008255cb23d7.png)
![captura de pantalla 2018-03-01 a las 11 39 19 a m](https://user-images.githubusercontent.com/30849540/36856981-59444968-1d45-11e8-89a8-f6843d752776.png)

- [ ] IOS
- [ ] 3.6.4
- [ ] 
- [ ]  I installed with pip install gplaycli
- [ ] i configure.config

**Comment by matlink** [comment]
try `mkdir ~/.cache`.

**Comment by ssaenz11** [comment]
![captura de pantalla 2018-03-01 a las 8 12 39 p m](https://user-images.githubusercontent.com/30849540/36878439-00a71626-1d8d-11e8-9c94-f4b38a72d5dc.png)
 now it says that i can not find de config file and i already create it.

**Comment by matlink** [comment]
Where did you out your config file? It should be either in the current directory or in `~/.config/gplaycli/gplaycli.conf`

**Comment by ssaenz11** [comment]
you where right it wasn't in the right place .  Thank you very much !

**Comment by ssaenz11** [comment]
now , i have tried a lot of AppID , and it shows me this
![captura de pantalla 2018-03-02 a las 3 54 39 p m](https://user-images.githubusercontent.com/30849540/36921353-14be6ccc-1e32-11e8-9c9b-b7bb94c0913f.png)

**Comment by matlink** [comment]
Fixed in 3.21
