### ISSUE TITLE
how can i call gplaycli from java or python 

### ISSUE THREAD

**Issue by ssaenz11** [matlink/gplaycli#169]
Hi , i already installed gplaycli (with your help , thank you for that) and it works in my terminal (I already installed an APK) , but now i want to call it from java or python .
with python i am using os.system("gplaycli -d APKID")
and with java
Runtime rt = Runtime.getRuntime();
		Process pr = rt.exec("gplaycli -d APKID");
the problem is that in java it cannot find the file and in python it shows me the number 32512, that i think means the same thing.

Thank you again!

**Comment by matlink** [comment]
Try to put the complete path to `gplaycli`. You can probably get it by running `which gplaycli`.
