### ISSUE TITLE
Make the source code pep8 compliant

### ISSUE THREAD

**Issue by raphael0202** [matlink/gplaycli#17]
The python source code is not pep8 compliant (indentation mix tabs and space, missing whitespaces,...).
If you agree I can submit a PR with a fully pep8 compliant code.

**Comment by matlink** [comment]
Of course, any PR is welcome since it doesn't break the code :)

Le 09/12/2015 18:52, raphael0202 a écrit :
>
> The python source code is not pep8 compliant (indentation mix tabs and
> space, missing whitespaces,...).
> If you agree I can submit a PR with a fully pep8 compliant code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matlink/gplaycli/issues/17>.
>

-- 
Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by raphael0202** [comment]
I submitted the PR

**Comment by matlink** [comment]
Yep thank you, I'll to test it before meging it to master :)

**Comment by raphael0202** [comment]
You're welcome ! I also have a couple of other PR with unreachable code removal/other cleanup

**Comment by matlink** [comment]
Yep, any improvement is welcome :)

Le 09/12/2015 19:28, raphael0202 a écrit :
>
> You're welcome ! I also have a couple of other PR with unreachable
> code removal/other cleanup
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matlink/gplaycli/issues/17#issuecomment-163349794>.
>

-- 
Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by matlink** [comment]
#18 merged. Re-open another issue for any other PR.
