### ISSUE TITLE
Bad gateway when calling the token URL

### ISSUE THREAD

**Issue by U039b** [matlink/gplaycli#170]
https://matlink.fr/token/email/gsfid returns a 502 error.

**Comment by shtrom** [comment]
Same here.

**Comment by matlink** [comment]
Should be ok. Sorry for the inconvenience.

**Comment by JetLiu92** [comment]
https://matlink.fr/token/email/gsfid returns a 502 error again.

**Comment by matlink** [comment]
I guess my IP address has been banned. Using a proxy, I'm able to checkin. I looking for a way to handle this (actually using tor might be a solution).

**Comment by matlink** [comment]
I fixed it temporarily by routing my traffic trough the Tor network. I'll see if it's a long-term solution.

**Comment by steve-jokes** [comment]
https://matlink.fr/token/email/gsfid returns a 502 error again.

**Comment by LXQBer** [comment]
502 Bad Gateway exception occurred when downloading with gplaycli today! ! !

**Comment by matlink** [comment]
See https://github.com/yeriomin/token-dispenser/issues/23
