### ISSUE TITLE
util.sizeof_fmt(...) raises ValueError on Windows for `gplaycli -s`

### ISSUE THREAD

**Issue by xennygrimmato** [matlink/gplaycli#171]
- Operating System: `Windows 10`
- Python version when running: `3.6`
- GPlayCli version via `gplaycli -v`: `3.21`
- The way you installed `gplaycli`: `pip3 install gplaycli`

I executed `gplaycli -s "paytm"` from the Windows Command Prompt.
`Line 5` in `util.py` raised `ValueError`. However, it worked fine on my Mac OS X (El Capitan).

The root cause for this seems to be that the argument passed to `util.sizeof_fmt(...)` is `<= 0`.

In the `search(...)` function in `gplaycli.py`, we should do a check on `result['installationSize']` to ensure that we only pass positive values to `util.sizeof_fmt(...)`.

We can display the size of such apps as `N/A` in the search output because installation size `0` doesn't make sense.

I can create a Pull Request to fix this.

**Comment by matlink** [comment]
I think the issue if before sizeof_fmt, because having a size <= 0 is not normal

**Comment by xennygrimmato** [comment]
Agreed. The only possibility I see is Google Play API returning <= 0 sometimes. Of course, ideally Google Play shouldn't return something like that, but what other reason could be causing this?
