### ISSUE TITLE
Android benign files

### ISSUE THREAD

**Issue by vinayakumarr** [matlink/gplaycli#173]
I want to download around 7000 benign apk files from google play. How to do this?

**Comment by vinayakumarr** [comment]
Is there any sample code to do this?

**Comment by matlink** [comment]
Put your 7000 packagenames in one file, on packagename per line, and do
```
gplaycli -F packages.txt
```
You might want to split your 7000 packages into different files to avoid bans, and do
```
gplaycli -F packages1.txt;
gplaycli -F packages2.txt
...
gplaycli -F packages14.txt
```
I don't know how many packages you can download in a row, but I recommend not to download more than 200 apps in a while. Then wait a couple of minutes an continue.

**Comment by nidauzel** [comment]
Can you download benign files? I also want to install lots of apks but I don't know how. Thank you for your answer.
