### ISSUE TITLE
Google asks for additional security check

### ISSUE THREAD

**Issue by kyak** [matlink/gplaycli#174]
Hi,

First of all, i've been using gplaycli for more than a year now without significant problems.
But recently (maybe a week ago), I've started seeing the authentication error in gplaycli:

[ERROR] Bad authentication, login or password incorrect ('Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password')

When I visit https://accounts.google.com/b/0/DisplayUnlockCaptcha, I enter my credentials and then click "Continue" button. I have to do it from the same IP that I later use gplaycli from, otherwise Google starts asking more questions.
After that, I can use gplaycli for some time (maybe an hour or so), and then I start seeing this authentication error again.
I've tried changing the password and enabling access to "less secure apps" in Google account, but it doesn't help. The account is used only for gplaycli, there is nothing else.

I could've switched to your token dispenser, but then the downloaded apps are for ARMv8 64 bit architecture, despite the fact that I supply "--device-codename wetekplay2" switch to gplaycli.

Any ideas what's causing the authentication issue?

More info:
- Operating System: Arch Linux
- Python version when running `gplaycli`: Python3.6.4
- GPlayCli version via `gplaycli -v`: GPlayCli version 3.21
- The way you installed `gplaycli`: via AUR
- The authentication method: own credentials

**Comment by kyak** [comment]
2FA is a no-go. Google wants a phone number.

**Comment by archon810** [comment]
I believe I've added a phone number, enrolled in 2FA, then enabled Authy, and then removed the phone number.

**Comment by kyak** [comment]
@archon810 Thanks for the hint! It's all is working fine now.

**Comment by matlink** [comment]
Indeed google has strengthened their detection of automatic play store fetching. 2FA + app password is the recommended combo to avoid this kind of issue.
