### ISSUE TITLE
Generating GSFID like https://matlink.fr/token/email/gsfid

### ISSUE THREAD

**Issue by yehgdotnet** [matlink/gplaycli#179]
Hello @matlink 

I used GSFID with tools from http://www.onyxbits.de/dummydroid and it returns only string like `3b94054b12fca0a5`. 

But I am wondering how you can generate GSFID string like your hosted site - https://matlink.fr/token/email/gsfid:

`DQYq052AIx9AyoEBoLplz_ZedhGR6ShWWfoQgES6I39WfSrdm3rkjZi8vZhiWiZapxz19w. 3b94054b12fca0a5`

If I don't use the correct format, I got the following error

> [INFO] GPlayCli version 3.22 [Python3.6.4]
> [INFO] Configuration file is ['../libs/gplaycli/gplaycli.conf']
> [INFO] Using cached token.
> [INFO] Using auto retrieved token to connect to API
> [INFO] Token has expired or is invalid. Retrieving a new one...
> [INFO] Retrieving token ...
> RuntimeWarning: Unexpected end-group tag: Not all data was converted
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/GPlayCli-3.22-py3.6.egg/gplaycli/gplaycli.py", line 406, in connect

Thank you very much

**Comment by matlink** [comment]
You also need the token (which is the first part of the string returned by my token dispenser).

**Comment by yehgdotnet** [comment]
Yes, I was wondering 
how to get that first part.  I wish at least dummydroid reveals simple copy-paste gsfid string.

**Comment by matlink** [comment]
Tokendispenser uses the google play api from @yeriomin
