### ISSUE TITLE
Free App Error App Not Purchased

### ISSUE THREAD

**Issue by ibrahimch** [matlink/gplaycli#181]
I'm facing a issue, i tried to download an application, it returns App not purchased, but application is free. App name is Youtube Go. (https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.mango)
---------------------------------------------------------------------
```
OS: Ubuntu 16.04
Python: Python3
-v Result
[INFO] GPlayCli version 3.21 [Python3.5.2]
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Using cached token.
Method: Installed using pip3
ConfigData:
[Credentials]
gmail_address=myemail
gmail_password=******
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
timezone=CEST
```

> PS: I'm downloading from php exec() function

**Comment by archon810** [comment]
You must be in a country where Youtube Go isn't available. It's geo limited.
