### ISSUE TITLE
Is androguard really required?

### ISSUE THREAD

**Issue by blshkv** [matlink/gplaycli#182]
I noticed a change of required packages in the last release.
That small change required 34 new python packages, mostly pulled by ipython-5:
```
~dev-python/ipython-5.4.1
~dev-python/ipyparallel-6.0.2
~dev-python/notebook-5.0.0
~dev-python/jupyter_client-5.1.0
~dev-python/nbconvert-5.2.1
~dev-python/mistune-0.7.4
~dev-python/entrypoints-0.2.3
~dev-python/qtconsole-4.3.1
~dev-python/ipykernel-4.6.1
~dev-python/testpath-0.3.1
~dev-python/pandocfilters-1.4.2
~dev-python/jupyter_core-4.4.0
~dev-python/nbformat-4.0.1
and many other
```

So the question: is androguard really required? Everything seems was working fine in the previous version

**Comment by matlink** [comment]
I was using pyaxmparser. However, it I'd not available in Debian packages, so I switched back to androguard. It is used to parse apk files to check for updates.

**Comment by blshkv** [comment]
that's a very strange problem. It wasn't available in Gentoo either, I just created an ebuild and the issue is fixed. Can't you request for its inclusion or help to create it? It must be a way to add a missing package.

**Comment by matlink** [comment]
Debian maintainers would prefer to maintain only one package for one given functionality. More over, it is a long process to add a package, longer than switching a dependency.

**Comment by matlink** [comment]
Why is it that important not to depend on it?

**Comment by blshkv** [comment]
I have exact opposite situation: there is no androguard in my system and I do not want to install 40 python packages, pollute my system, waste space and also support them all (in Pentoo) in order just to be able to parse AXM files. 

pyaxmlparser 28kb package does it well.

**Comment by matlink** [comment]
Well I guess we should support both then. But I don't know how manageable is this solution...

**Comment by matlink** [comment]
androguard has been replaced by pyaxmlparser in version 3.23 d1b085805f2b960fb2860de2a4bc8a213e1b77be

**Comment by blshkv** [comment]
Great, thank you!
