### ISSUE TITLE
Feature: Output directory election when downloading from lists (-F)

### ISSUE THREAD

**Issue by enovella** [matlink/gplaycli#184]
Actual command:
```
 -f FOLDER, --folder FOLDER
                        Where to put the downloaded Apks, only for -d command
```

Suggested:
```
 -f FOLDER, --folder FOLDER
                        Where to put the downloaded Apks, only for -d, -F commands
```

**Comment by matlink** [comment]
I guess you should be clearer with your question. I needed to read it multiple times to understand it.
So basically, you want the '-f' option to work also with the '-F' one?

**Comment by enovella** [comment]
My bad for the brief and unclear explanation. 

The command ` gplaycli -v -p -F /tmp/list_00 -f /tmp/` works okay  but the help wasnt clear.

**Comment by matlink** [comment]
Oh, that's just a documentation improvement. Gotcha.
