### ISSUE TITLE
any hint on how to reveal the actual URL of the apk download?

### ISSUE THREAD

**Issue by atwleung** [matlink/gplaycli#185]
I can run the script okay, here is a sample run for downloading facebook messenger:
./gplaycli -v -d com.facebook.orca
[INFO] GPlayCli version 3.23 [Python3.5.2] 
[INFO] Configuration file is gplaycli.conf
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[INFO] 1 / 1 com.facebook.orca
[INFO] Download complete

My question is, if I would like to view the actual URL utilized during the download, how should I modify the script to achieve this?

Please provide those informations:

- [x] Operating System (ie Ubuntu 16.04)
Ubuntu 16.04.3 LTS
- [x] Python version when running `gplaycli` (should be 3+)
Python3.5.2
- [x] GPlayCli version via `gplaycli -v`
[INFO] GPlayCli version 3.23 [Python3.5.2] 
- [x] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
pip install gplaycli
- [x] The authentication method: (own) credentials or (own) token.
own credentials.

**Comment by matlink** [comment]
yeah in gpapi you get that URL but you should install a customized version of it.
