### ISSUE TITLE
Include an option to specify abi

### ISSUE THREAD

**Issue by Baschdl578** [matlink/gplaycli#187]
Right now, I am using glpaycli on arch linux (with python 3.6.5).
I have it setup so that it loads all apks in a list to my fdroid repo.

But some apps (in my case WhatsApp and Google Maps) will download versions only compatible with arm64-v8a, which i can't run on my phone (f-droid lists as incompatible)
I thought specifying the device codename ("bacon" for me) would help, but it did not change anything.

Is it possible to include an option to specify the abi of my target device or even get that information from the device codename?

**Comment by wickedsp1d3r** [comment]
I have exactly the same question/request.

For example when I issue
```
gplaycli -dc JP-1601 -s whatsapp -n 1
```
Instead of `452385` (arm-v7a) the returned version is `452387` (arm64-v8a).

**Comment by matlink** [comment]
Yeah, this change has to be done server-side. Now by default, tokens are generated for bacon device, then armeabi-v7a arch. Should be compatible with most of the devices.
I'll probably implement the option to change the device, as the one currently implemented is not working.

**Comment by matlink** [comment]
Use a device codename which corresponds to the abi you want.
