### ISSUE TITLE
Lots of warnings pollute output

### ISSUE THREAD

**Issue by kyak** [matlink/gplaycli#188]
Hi,

There are masses and masses of warnings that get spitted out during usage of gplaycli. By this I mean around 9176 lines of output from simply running /usr/bin/gplaycli --update.

Examples of such warnings:

    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000ab70c' type='514' header_size='16' size='160'>
     warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000ab7ac' type='513' header_size='76' size='796'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscutil.py:181: UserWarning: Skipping padding bytes!
      warn("Skipping padding bytes!")
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 0, 0, 0, 0, 0, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abac8' type='513' header_size='76' size='252'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 0, 0, 0, 0, 21, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abbc4' type='514' header_size='16' size='20'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abbd8' type='513' header_size='76' size='96'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abc38' type='514' header_size='16' size='40'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abc60' type='513' header_size='76' size='604'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abebc' type='513' header_size='76' size='284'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 25954, 0, 0, 0, 0, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000abfd8' type='513' header_size='76' size='284'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 27509, 0, 0, 0, 0, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000ac0f4' type='513' header_size='76' size='116'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 29300, 0, 0, 0, 0, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x000ac168' type='513' header_size='76' size='284'>
      warn("Found a header: {}".format(pkg_chunk_header))
    /usr/lib/python3.6/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 30066, 0, 0, 0, 0, 0, 0)'>
      warn("Config: {}".format(a_res_type.config))

And it goes on, and on, and on...

Other than that, gplaycli works fine (apks get updated).

- [Arch Linux]
- [Python 3.6.5]
- [GPlayCli version 3.23]
- [Installed from AUR]
- [Auth: own credentials]

**Comment by matlink** [comment]
That's pyaxmlparser's warnings. I can't see why it happens, nor where.

**Comment by kyak** [comment]
Looks like pyaxmlparser pulled some recent changes, which contain warnings for debugging purposes.

**Comment by kyak** [comment]
@matlink would it be possible for you to implement the workaround such as described in https://github.com/appknox/pyaxmlparser/issues/19#issuecomment-403294972?

**Comment by matlink** [comment]
Still have those warnings?

**Comment by kyak** [comment]
Yes, nothing's changed.

**Comment by kyak** [comment]
@matlink Any good reason why you closed this issue? Do you not reproduce this problem? The output is basically not readable because of this :disappointed:

**Comment by mike10191** [comment]
@kyak @matlink I think this issue should be reconsidered:

/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f2234' type='513' header_size='76' size='3036'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f2e10' type='513' header_size='76' size='3068'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f3a0c' type='513' header_size='76' size='3756'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f48b8' type='513' header_size='76' size='3116'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f54e4' type='513' header_size='76' size='3036'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f60c0' type='513' header_size='76' size='3036'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f6c9c' type='513' header_size='76' size='3036'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:120: UserWarning: Config: <ARSCResTableConfig '(0, 0, 0, 0, 0, 20, 0, 0)'>
  warn("Config: {}".format(a_res_type.config))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f7878' type='513' header_size='76' size='3068'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f8474' type='513' header_size='76' size='3052'>
  warn("Found a header: {}".format(pkg_chunk_header))
/usr/local/lib/python3.7/site-packages/pyaxmlparser/arscparser.py:105: UserWarning: Found a header: <ARSCHeader idx='0x007f9060' type='513' header_size='76' size='3052'

**Comment by matlink** [comment]
No, I'm not gonna apply this workaround. Let me explain:

- if I want people not having these warnings, I need to publish a new release with that workaround. However, it is not worth a release for me.

- second option: put it in master so people having this issue can use the upstream version. It requires a manual installation. Less burder option to me is to downgrade pyaxmlparser to the previous version that does not pollute output with warnings.

Unless I have a clean way to mute only these warnings (which is not the case of the proposed solution), it's pyaxmlparser that has to fix it.

**Comment by subho007** [comment]
@matlink how does this https://github.com/appknox/pyaxmlparser/pull/28 looks like? I hope this will stop polluting the warnings

**Comment by subho007** [comment]
I have released a newer version, please update to `pyaxmlparser==0.3.13`
