### ISSUE TITLE
fdroid update of simple binary repo does nothing

### ISSUE THREAD

**Issue by abeudin** [matlink/gplaycli#19]
https://f-droid.org/forums/topic/fdroid-update-of-simple-binary-repo-does-nothing/#post-10698

i try to do it remove the apk with the name of version and it's work.

**Comment by matlink** [comment]
I don't understand the matter

**Comment by matlink** [comment]
Related to https://github.com/matlink/gplaycli/issues/4 ?

**Comment by matlink** [comment]
`fdroid update -c --clean` can check every apk if it has update, no need to rename them.
