### ISSUE TITLE
Use gplaycli from python 

### ISSUE THREAD

**Issue by hanjideng** [matlink/gplaycli#190]
### I  use the  gplaycli from  python as
```
import gplaycli
gpc = gplaycli.GPlaycli()
gpc.token_url = 'http://xxxx.xx:xxxx/email/gsfid'
gpc.token_enable = True
gpc.set_download_folder('.')
ret = gpc.download([['com.leo.basex', 'tmp.tmp']])
```
### but it  went wrong:
```
File "/test.py", line 77, in <module>
    ret = gpc.download([['com.leo.basex', 'tmp']])
  File "/Users/xxx/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/Users/job/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 405, in connect
    authsub_token = self.token
AttributeError: 'GPlaycli' object has no attribute 'token'
```

**Comment by matlink** [comment]
use `gpc.retrieve_token(force_new=True)` before downloading.
I know it has to be handled by the hook.

**Comment by hanjideng** [comment]
### Thanks, it's worked
### But it seems that using from python is too confused, maybe we can use `init()` or somthing else

**Comment by matlink** [comment]
After thinking about it, it is expected if using gplaycli from python you have to manually retrieve the token. For sake of universality and simplicity, when you use it from python, gplaycli runs as few as possible automatic procedures.
