### ISSUE TITLE
Make gplaycli more robust when token is invalid

### ISSUE THREAD

**Issue by leegarrett** [matlink/gplaycli#191]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- Debian stretch (9.4)
- Python 3.5.3
- [ ] GPlayCli version via `gplaycli -v`
- pip3 install gplaycli
- token

I was always getting the following output running gplaycli:
```
$ gplaycli -d com.imgur.mobile -v
[INFO] GPlayCli version 3.23 [Python3.5.3] 
[INFO] Configuration file is /var/www/fdroid/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
Traceback (most recent call last):
  File "/var/www/fdroid/.local/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/var/www/fdroid/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 702, in main
    cli.download(args.packages_to_download)
  File "/var/www/fdroid/.local/lib/python3.5/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/var/www/fdroid/.local/lib/python3.5/site-packages/gplaycli/gplaycli.py", line 406, in connect
    gsfid = int(self.gsfid, 16)
ValueError: invalid literal for int() with base 16: 'reset'
```

After some digging around I found the following issue:
```
fdroid@packages:~$ cat .cache/gplaycli/token 
Connection resetfdroid@packages:~$ python3.5 -v
```

So it seems as though at some point in time gplaycli couldn't fetch a token and wrote a literal "Connection reset" (without CR/LF) into the token cache.

So it seem as though gplaycli is missing some sanity checks on the token file. Deleting the token made it run without throwing a traceback again.

**Comment by leegarrett** [comment]
The other variant I get is:
```
fdroid@packages:~/gplaycli/repo$ cat ~/.cache/gplaycli/token 
Malformed requestfdroid@packages:~/gplaycli/repo$ 
```

Let me see if I find some time tomorrow to fix this.

**Comment by eighthave** [comment]
Just deleting it didn't work for me, I had to do:
```console
$ rm ~/.cache/gplaycli/token
$ touch ~/.cache/gplaycli/token
```
