### ISSUE TITLE
gpapi.googleplay.SecurityCheckError

### ISSUE THREAD

**Issue by juandiazq** [matlink/gplaycli#199]
When I try to update a folder with apks, I get a SecurityCheckError:

`[INFO] GPlayCli version 3.24 [Python3.6.5] `
`[INFO] Configuration file is $HOME/.config/gplaycli/gplaycli.conf`
`[INFO] Checking apks ...`
`[INFO] Using credentials to connect to API`
`[INFO] Using plaintext password`
`Traceback (most recent call last):`
 ` File "$HOME/programs/gplaycli-vm/bin/gplaycli", line 11, in <module>
    sys.exit(main())`
 ` File "$HOME/programs/gplaycli-vm/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 707, in main cli.prepare_analyse_apks()`
`  File "$HOME/programs/gplaycli-vm/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 500, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, download_folder)`
 ` File "$HOME/programs/gplaycli-vm/local/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection self.connect()`
`  File "$HOME/programs/gplaycli-vm/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 430, in connect gsfId=gsfid)`
`  File "$HOME/programs/gplaycli-vm/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 223, in login
    raise SecurityCheckError()`
`gpapi.googleplay.SecurityCheckError`

- Ubuntu 18.04 bionic
- Python 3.6.5
- [INFO] GPlayCli version 3.24 [Python3.6.5] 
- [INFO] Configuration file is $HOME/.config/gplaycli/gplaycli.conf
- `gplaycli` Setup: using `virtualenv $HOME/programs/gplaycli-vm`, `source $HOME/programs/gplaycli-vm/bin/activate` and then `pip install gplaycli`
- The authentication method:  using my own credentials and a google app password. Google 2-step auth is enabled.

**Comment by matlink** [comment]
Check https://github.com/NoMore201/googleplay-api/issues/67
