### ISSUE TITLE
support system installation

### ISSUE THREAD

**Issue by blshkv** [matlink/gplaycli#200]
Hi I'm trying to port this tool to pentoo Linux and having a problem with installing it as a system tool.
The setup.py is installing to a "current" user (```~``` folder):
```
                data_files=[                                                                                            
                        [os.path.expanduser('~')+'/.config/gplaycli', ['gplaycli.conf','cron/cronjob']],                
                ], 
```
which is NOT available during installation.

I suggest to install it to a system directory by default (/etc) and  use a local copy to overwrite it if user decided to make any changes.

**Comment by matlink** [comment]
No because it would not be possible to install it using pip and --user

**Comment by blshkv** [comment]
I have actually patched that line and it used to work. But something wrong goes with the latest version.

**Comment by matlink** [comment]
I guess if you want to port this tool systemwide you probably should not rely on setup.py

**Comment by blshkv** [comment]
```gplaycli -c /etc/gplaycli/gplaycli.conf -d com.google.android.youtube.tv
Exception ignored in: <_io.FileIO name='/home/xxx/.cache/gplaycli/token' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/xxx/.cache/gplaycli/token' mode='r' encoding='UTF-8'>
Token dispenser auth error, probably too many connections
```

**Comment by matlink** [comment]
This is unrelated to this issue. It comes from the fact that too many requests are currently done with my token-dispenser instance.

**Comment by blshkv** [comment]
ok, ignore it. Please provide an option for systewide install. If not, it would be the only tool in the World with a proper setup.py which works with ```--user``` option only.

**Comment by matlink** [comment]
Don't confuse this line `os.path.expanduser('~')+'/.config/gplaycli', ['gplaycli.conf','cron/cronjob']` with the location where `gplaycli` binary will be installed. This line is for `data_files` (configuration files).

**Comment by matlink** [comment]
BTW if you want to install it systemwide, run `sudo pip3 install gplaycli` and it will be placed in default system directory for python, like `/usr/local/bin/gplaycli` for me .

**Comment by blshkv** [comment]
yes, I understand. We install all tools in a sandbox (Gentoo portage) and home directory is not defind during that installation

**Comment by blshkv** [comment]
so again, everything works fine when I install it except that I need to patch that line in the setup.py.
gplaycli.py also finds the same config because of the following line:
https://github.com/matlink/gplaycli/blob/master/gplaycli/gplaycli.py#L85

can you install it into ````/.config/gplaycli/``` if --user option is specified and into /etc if it is not?

**Comment by blshkv** [comment]
correct me if I'm wrong. But the --user option means it will be installed into ```~/.local/lib``` and ```~/.local/etc``` This is where it belongs. You should only try to ***read*** user's config (and prioritize its settings) ***if* user created it manual his home folder (```~/.config/gplaycli```)

**Comment by matlink** [comment]
Linked to #242
