### ISSUE TITLE
pip install fails with error

### ISSUE THREAD

**Issue by Flashwalker** [matlink/gplaycli#202]
- [Android] Operating System (ie Ubuntu 16.04)
- [3.7] Python version when running `gplaycli` (should be 3+)
- [3.25] GPlayCli version via `gplaycli -v`
- [pip install gplaycli] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ ] The authentication method: (own) credentials or (own) token.

pip Installation fails on Android on Termux.
Install log:https://ptpb.pw/Yq6z/bash

**Comment by matlink** [comment]
I already tried to install on tmux but it seems to fail the compilation of some dependencies. It's not a gplaycli issue but more likely a protobuff one.

**Comment by XATEV** [comment]
Install on Ubuntu using pip3 works, but fails executing gplaycli.
```
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 28, in <module>
    from androguard.core.bytecodes import apk as androguard_apk  # Androguard
ImportError: No module named androguard.core.bytecodes
```
I did install all requirements.

**Comment by Flashwalker** [comment]
There is an opinion that it might be an issue of support openssl 1.1.1, is it right guess?

**Comment by Grimler91** [comment]
Looking at the log again I see that the error occurs when installing cryptography (as @matlink hinted). @Flashwalker are your packages up to date? (Have you run `pkg upgrade`?) This error shouldn't occurs for cryptography with up to date packages

**Comment by Flashwalker** [comment]
Ok. Upgrade fixed that. But not this: https://ptpb.pw/6nud/bash
libxml2* is installed but pip said: no, bro.

**Comment by Grimler91** [comment]
Quote from your log: `make sure the development packages of libxml2 and libxslt are installed`
So install libxml2-dev and libxslt-dev..

**Comment by Flashwalker** [comment]
Oh, missed libxslt* to. Ok, now all of crap is installed. Gplaycli works. Nicely. Thnx guys, +10 for your logreading skill.
