### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 'fr'

### ISSUE THREAD

**Issue by Swetha-Gorantla** [matlink/gplaycli#204]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ ] Operating System - AWS Linux 4X large
- [ ] Python version when running - Python 2
- [ ] The authentication method: (own) credentials.

I am logging into a web application and trying to get some data. In this process, I am planning to do a get request to an URL which is the output of a variable as below...

`d = {'Mango': 'http://12.345.67.891:8000/api/datasources/proxy/1/query?db=UK_GHS&q=SELECT%20sum(%22count%22)%20FROM%20%22gatling%22%20WHERE%20%22status%22%20%3D%20%27ok%27%20AND%20%22simulation%22%20%3D~%20%2Fsoak-test*%2F%20AND%20time%20%3E%from{}ms%20and%20time%20%3C%to{}ms%20GROUP%20BY%20%22script%22&epoch=ms',
 'Banana':'http://12.345.67.891:8000/api/datasources/proxy/1/query?db=UK_GHS&q=SELECT%20sum(%22count%22)%20FROM%20%22gatling%22%20WHERE%20%22status%22%20%3D%20%27ok%27%20AND%20%22simulation%22%20%3D~%20%2Fspike-test*%2F%20AND%20time%20%3E%from{}ms%20and%20time%20%3C%to{}ms%20GROUP%20BY%20%22script%22&epoch=ms',
 'Apple':'http://12.345.67.891:8000/api/datasources/proxy/1/query?db=UK_GHS&q=SELECT%20sum(%22count%22)%20FROM%20%22gatling%22%20WHERE%20%22status%22%20%3D%20%27ok%27%20AND%20%22simulation%22%20%3D~%20%2Fload-test*%2F%20AND%20time%20%3E%from{}ms%20and%20time%20%3C%to{}ms%20GROUP%20BY%20%22script%22&epoch=ms'}   

def user_input_to_epoch_time(user_input):
    return int(time.mktime(time.strptime(user_input, '%Y-%m-%d %H:%M:%S')))

Dashboard_name = raw_input("Enter dashboard name from the above list :")
user_input_from = raw_input("Enter from date and time in YYYY-MM-DD HH:MM:SS format :")
user_input_to = raw_input("Enter to date and time in YYYY-MM-DD HH:MM:SS format :")    

final_url = d[Dashboard_name].format(user_input_to_epoch_time(user_input_from),
                                  user_input_to_epoch_time(user_input_to))
print(final_url)`

POST this step I am getting final URL as below...

`http://12.345.67.891:8000/api/datasources/proxy/1/query?db=UK_GHS&q=SELECT%20sum(%22count%22)%20FROM%20%22gatling%22%20WHERE%20%22status%22%20%3D%20%27ok%27%20AND%20%22simulation%22%20%3D~%20%2Fsoak-test*%2F%20AND%20time%20%3E%201544491800000ms%20and%20time%20%3C%201544495400000ms%20GROUP%20BY%20%22script%22&epoch=ms`

For this final URL, I wanted to do a get request and I am doing it as below.

`results = s.get(final_url) #s is the variable where i stored my session attributes ' s = requests.Session()'
resultsres = results.content
print(resultsres)`

When I am doing the GET request for the final_URL I am getting below error

`ValueError: invalid literal for int() with base 16: 'fr'`

 Can someone help me how to resolve this issue?

**Comment by matlink** [comment]
Please tell me if it is related to gplaycli.
Btw, gplaycli is python3-compatible only.
