### ISSUE TITLE
Results truncated to 25 maximum.

### ISSUE THREAD

**Issue by dkfulp** [matlink/gplaycli#205]
Operating System Ubuntu 18.04
[INFO] GPlayCli version 3.25 [Python3.6.7]
[INFO] Configuration File is gplaycli.conf
[INFO] Device is bacon
[INFO] Using cached token.

I am running the following command in terminal:
gplaycli -s vpn -n 1000

But it still truncates them to 25.  Do you know why this is and how to get all results?

**Comment by matlink** [comment]
This is a bug.
