### ISSUE TITLE
Outdated version of applications from Google Play 

### ISSUE THREAD

**Issue by lluke777** [matlink/gplaycli#206]
- Windows 7 64bit
-  Python 3.6.3
-  GPlayCli 3.25
-  pip install gplaycli
- credentials

Some applications downloaded by gplaycli seems to be outdated. 
Example: 
`gplaycli -s revolut`
Version name: 5.12
Version code: 501200373

while downloaded directly from Google Play:
Version: 5.38

Does gplaycli use some mirror that is updated with delay?  I guess it is not possible to get uptodate applications directly from google play servers?

**Comment by matlink** [comment]
Gplaycli does not use any mirror. It downloads the files directly from Google servers.
However, the default device that is emulated to talk to Google servers may have an outdated available version of the application. Try using a different device.

**Comment by lluke777** [comment]
For some reasons:
`gplaycli -d com.revolut.revolut -dc angler`
gives me random results it is either:
1.  `Error while downloading com.revolut.revolut : 'Your device is not compatible with this item.'
A few packages could not be downloaded :
com.revolut.revolut
'Your device is not compatible with this item.'`

2. `Bad authentication, login or password incorrect ('server says: UNKNOWN_ERR')
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
 .
 .
 .
`
3. Downoads file with newest version but corrupted ony 22Mb in size instead about 50Mb
