### ISSUE TITLE
Does this download from mox.matlink.fr instead of Google Play?

### ISSUE THREAD

**Issue by aario** [matlink/gplaycli#208]
On `iftop` I see the application contacts:
```
mox.matlink.fr
```
Does this download from mox.matlink.fr instead of Google Play? Is there a way to download only from google servers? Does the software also upload information to this private server?

Please provide those informations:

- [x] Operating System (ie Ubuntu 16.04)
Debian Sid
- [x] Python version when running `gplaycli` (should be 3+)
3.7.3
- [x] GPlayCli version via `gplaycli -v`
3.25
- [x] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
```
apt install --no-install-recommends gplaycli
```
- [x] The authentication method: (own) credentials or (own) token.
Just default

**Comment by matlink** [comment]
The communication with `mox.matlink.fr` is to get the token from my token-dispenser instance. Then gplaycli communicates with the play store to execute your request.
