### ISSUE TITLE
Unregistered Email and Android-ID not able to simulate real download on PlayStore

### ISSUE THREAD

**Issue by tahseenjamal** [matlink/gplaycli#21]
I created a new email id and fetched android-id from a phone.

I used these credentials to download an app. Then I logged using the credentials through web to playstore

I saw that it was not showing that app as installed on PlayStore.

There should be a way to register an email / android id and simulate real download through gplaycli such that even when I log into website using credentials, I can see the app downloaded there and the account shows device attached to that account, instead of showing "No Device Attached"

**Comment by matlink** [comment]
What for ?
