### ISSUE TITLE
Does this still work for downloads???

### ISSUE THREAD

**Issue by tugimuses** [matlink/gplaycli#210]
Installed using pip on Windows tried using credentials auth method but got gpapi.googleplay.SecurityCheckError so switched to token auth using matlink server I can search for packages fine but when I try to download I get 'Server busy, please try again later.' or 'Your device is not compatible with this item.'

gplaycli -t -tu https://matlink.fr/token/email/gsfid -p -L -vd org.mozilla.firefox -dc hammerhead

I have not been able to download any APKs anyone else have this problem does this still work?

**Comment by onny** [comment]
Yesterday it worked but today it seems to have issues

**Comment by Mutt-Huyh** [comment]
Since yesterday I get this:
```
Bad authentication, login or password incorrect ('server says: UNKNOWN_ERR')
Traceback (most recent call last):
  File "gplaycli", line 742, in <module>
    main()
  File "gplaycli", line 723, in main
    cli.prepare_analyse_apks()
  File "gplaycli", line 516, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, download_folder)
  File "/usr/lib/python3.4/site-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/gplaycli3", line 541, in analyse_local_apks
    details = self.api.bulkDetails(package_bunch)
  File "/usr/lib/python3.4/site-packages/gpapi/googleplay.py", line 378, in bulkDetails
    content_type="application/x-protobuf")
  File "/usr/lib/python3.4/site-packages/gpapi/googleplay.py", line 273, in executeRequestApi2
    raise Exception("You need to login before executing any request")
Exception: You need to login before executing any request
```

**Comment by Mutt-Huyh** [comment]
After changing to token based login it seems to work again. Is username login not possible anymore?

**Comment by microchipster** [comment]
> After changing to token based login it seems to work again. Is username login not possible anymore?

Could you explain how to setup the token based login? The documentation is quite unclear to me. Sorry if it's trivial...

**Comment by matlink** [comment]
Try again. To run your own token dispenser, check https://github.com/matlink/token-dispenser and change URL in your config file.
