### ISSUE TITLE
gpapi.googleplay.RequestError: 'Error while retrieving information from server. DF-DFERH-01'

### ISSUE THREAD

**Issue by ofskymohsen** [matlink/gplaycli#214]
- [Ubuntu 16.04] Operating System (ie Ubuntu 16.04)
- [3] Python version when running `gplaycli` (should be 3+)
- [3.25] GPlayCli version via `gplaycli -v`
- [pip install gplaycli] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [token] The authentication method: (own) credentials or (own) token.

when I enter command `gplaycli --update .` for updating APK files in a directory I encounter with this error:

`gpapi.googleplay.RequestError: Error while retrieving information from server. DF-DFERH-01`

How can I solve this problem?

**Comment by matlink** [comment]
It happens when the token has expired. New gplaycli version (3.26) now handles this case.
