### ISSUE TITLE
"Malformed request" when running "gplaycli -v"

### ISSUE THREAD

**Issue by xulifan** [matlink/gplaycli#216]
Does anyone know what went wrong?

```
➜  AWS gplaycli -v
[INFO] GPlayCli version 3.25 [Python3.5.2] 
[INFO] Configuration file is /home/lxu/.config/gplaycli/gplaycli.conf
[INFO] Device is bacon
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token/email/gsfid/bacon
[ERROR] Unknowned error: Malformed request
```

It looks like retrieve_token() inside gplaycli.py returns Malformed request when query [https://matlink.fr/token/email/gsfid](https://matlink.fr/token/email/gsfid).

**Comment by tygh-cpu** [comment]
Noticed it is happening on all token generators I think Google have updated the API

**Comment by xulifan** [comment]
It looks like [](https://matlink.fr/token/email/gsfid) returns Malformed request.

**Comment by matlink** [comment]
I have updated the token dispenser server.
