### ISSUE TITLE
How to use proxy to search and download

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#218]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [windows ] Operating System (ie Ubuntu 16.04)
- [python3+ ] Python version when running `gplaycli` (should be 3+)
- [3.25 ] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

How to use commands such as - s com. herocraft. game. free. deadshell -- proxy 11.11.11:12345

**Comment by delthas** [comment]
In your shell:
```shell
export HTTP_PROXY="http://11.11.11:12345"
export HTTPS_PROXY="http://11.11.11:12345"
gplaycli com.herocraft.game.free.deadshell
```

**Comment by LXQBer** [comment]
> 如果你在Linux上，在你的shell中：
> 
> ```shell
> export HTTP_PROXY = “ http：//11.11.11：12345 ”
>  export HTTPS_PROXY = “ http：//11.11.11：12345 ” 
> gplaycli com.herocraft.game.free.deadshell
> ```
> 
> 如果您在Windows上，在cmd.exe或批处理脚本中：
> 
> ```batchfile
> 设置 HTTP_PROXY = “ http：//11.11.11：12345 ”
> 设置 HTTPS_PROXY = “ http：//11.11.11：12345 ” 
> gplaycli com.herocraft.game.free.deadshell
> ```
> 
> 或者其他的东西。阅读[＃141](https://github.com/matlink/gplaycli/issues/141)和[请求库文档](https://2.python-requests.org//en/master/user/advanced/#proxies)。

Thank you for your answer

**Comment by matlink** [comment]
Proxy configuration is not bind gplaycli, you should configure the proxy using your network manager (or using the shell).
