### ISSUE TITLE
Why is there no application to search in the search results?

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#220]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [windows ] Operating System (ie Ubuntu 16.04)
- [3+ ] Python version when running `gplaycli` (should be 3+)
- [ ] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ ] The authentication method: (own) credentials or (own) token.
Why is there no application to search in the search results?

**Comment by LXQBer** [comment]
When I searched for com. supercell. rush, there was no com. supercell. rush in the returned results.

**Comment by matlink** [comment]
It is not compatible with 'bacon' device. If you find a compatible device, please try with its codename using option '-dc'.
