### ISSUE TITLE
What about splited apk?

### ISSUE THREAD

**Issue by muzzyrost** [matlink/gplaycli#223]
Hello, Matlink! Google added new way for delivery apk files - splitted apk (https://developer.android.com/guide/app-bundle). Some apps become splitted in few file - main file, some architecture libraries, languages and resources for different screen density. For now your app download just main file, which can`t start after installation. If you need any information for testing just let me know.

**Comment by matlink** [comment]
Have you tried with "additional files" option?

**Comment by muzzyrost** [comment]
"Additional files" don't help with it. It just adding download of .obb files.

**Comment by dilinger** [comment]
FYI, gpapi added support for split apks; it was merged in this PR:

https://github.com/NoMore201/googleplay-api/pull/108

They haven't done a release yet

**Comment by jr3074** [comment]
waiting for the release,
so many app cannot be installed to devices

**Comment by matlink** [comment]
Yeah, I can put it be I need @NoMore201 to publish a release =)

**Comment by matlink** [comment]
@muzzyrost @jr3074 have you got an example that I can download?

**Comment by muzzyrost** [comment]
@matlink yes, just try

- com.alibaba.aliexpresshd
- com.anydo
- org.wordpress.android
