### ISSUE TITLE
How would I go about downloading purchased apks?

### ISSUE THREAD

**Issue by thebunnyrules** [matlink/gplaycli#226]
Please provide those informations:

OS: Ubuntu 19.04
python: 3.7
gplaycli: 3.25
install method: apt-get install
what authentication method? 

I was just wondering if there is a set way to go about downloading apps I paid for? the issue info request hints at an authentication method. Is there any instructions as to how I can do this somewhere?

**Comment by matlink** [comment]
if you bought the app, just use your credentials in the config file and
download it like a free app.

Le 11/09/2019 à 22:03, thebunnyrules a écrit :

**Comment by matlink** [comment]
if you bought the app, just use your credentials in the config file and
download it like a free app.

**Comment by thebunnyrules** [comment]
Ah, perfect. Thanks for that. I'll test it.
