### ISSUE TITLE
Token dispenser auth error

### ISSUE THREAD

**Issue by simpnu** [matlink/gplaycli#228]
Hi!

We are currently getting the following error when trying to use GPlayCli to download an APK:
`[ERROR] Token dispenser auth error, probably too many connections`

Python version tested: 3.6 & 3.5
GPlayCli version tested: 3.25 & 3.26 (installed with pip)
The issue is present using your token dispenser or a freshly created local one.

Any idea where could the problem come from?
Thanks a lot!

**Comment by xulifan** [comment]
Got the same issue.

**Comment by CayoSouza** [comment]
Same.

**Comment by simpnu** [comment]
We fixed the issue for our token dispenser by updating to the latest version of this repository and restarting it.

I'm gonna let the issue open because it seems the TD hosted on matlink.fr still has the issue

**Comment by nottoobad** [comment]
Same here.
BTW How to use my own Google Credentials?

**Comment by matlink** [comment]
@simpnu how concretely did you fixed it? yeriomin has not pushed code for a long time.

**Comment by simpnu** [comment]
@matlink Unfortunately I don't have many details to give you. AFAIK we were not using the latest version from your repository, so we pulled the latest changes and restarted the TD and it magically started to work again.

@jfoucry do you have more details to give to @matlink ?

**Comment by jfoucry** [comment]
Sorry, but I did not have more details. Simply stopping TD, git pull restart TD.

Our TD run in a tmux, not demonized.
```
# git log -1
commit 3c74004a5aafea8b28a73caeb510f066b0b45bd2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 287f03e 277fe12
Author: Matlink <matlink@matlink.fr>
Date:   Fri Aug 30 21:05:05 2019 +0200

    Merge branch 'dev'
```
Hope this help

**Comment by simpnu** [comment]
**Update:**
Instead of getting sometimes "Auth error" and sometimes succeeding, we now have sometimes "Auth error" and sometimes "Malformed request" (and never succeeding).

:disappointed:

**Comment by Simon-Bouget** [comment]
Hey hey o/
Any news on that front, or is this out of your hand and we should start looking for other solutions?
Thanks for your work anyway :-)

**Comment by leegarrett** [comment]
Does anyone have an update for this? Many messengers I rely on getting via gplaycli have already given me warnings that they will expire soon. I tried using my own credentials, but they got deactivated after a few tries, so I think gplaycli is doing something that causes Google to blacklist the credentials, and the token dispenser might be working as expected. Just that the underlying credentials get deactivated by the gplaycli instances that consume the tokens.

**Comment by simpnu** [comment]
For the record, what we are doing now is to use gplaycli **without the token dispenser** as it doesn't seem to want to work anymore and use directly a GMail account in gplaycli configuration (with the fix I'm mentioning here https://github.com/matlink/gplaycli/issues/231).

If you use MFA and an application password it should work fairly well.

**Comment by Simon-Bouget** [comment]
@simpnu  Thanks for the heads-up, but when I do that I run afoul of Google so-called "Security Check". As in, my credentials are right, but the use isn't recognized (of course, I'm trying something new...) and they don't let me connect anyway. How did you solve that on your side? Is that why you mentioned "application password"? What's that?

(Also, as a long term solution, I'm a bit paranoid with having my password in clear in the config file. But well, at least it works as a temporary work-around.)

**Comment by wdormann** [comment]
FWIW, I'm not sure if the gplaycli code in github by default will accept non-token authentication.  If you look at https://github.com/matlink/gplaycli/blob/master/gplaycli/gplaycli.py#L600 , you'll see that default=True, which will result in the gplaycli command-line tool to use tokens, as instructed by https://github.com/matlink/gplaycli/blob/master/gplaycli/gplaycli.py#L150
This overrides any token_enable option that is derived from the config file earlier in __init__ at https://github.com/matlink/gplaycli/blob/master/gplaycli/gplaycli.py#L102

I spent more than I'd like to admit in troubleshooting this, but I finally realized that the Google Play server **always** responds with CaptchaRequired when the traffic is being MITM'd for inspection with CERT Tapioca (mitmproxy).  Regardless of whether an Application Password is used or not!  So in a sad heisenbug sort of situation, my inspection of traffic between myself and Google was the very thing that was ensuring that I'd always get a captcha.  I suppose the server is perhaps doing something like JA3 fingerprinting on the client, and is behaving differently based on what sort of client initiates the HTTPS connection.

**Comment by simpnu** [comment]
> @simpnu Thanks for the heads-up, but when I do that I run afoul of Google so-called "Security Check". As in, my credentials are right, but the use isn't recognized (of course, I'm trying something new...) and they don't let me connect anyway. How did you solve that on your side? Is that why you mentioned "application password"? What's that?

If I recall correctly you need to use the latest version of gpapi (0.4.4) to solve this issue.

An "application password" is a password you can generate for your Google account when there is MFA enabled. See https://support.google.com/mail/answer/185833?hl=en
