### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#229]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ windows] Operating System (ie Ubuntu 16.04)
- [3+ ] Python version when running `gplaycli` (should be 3+)
- [3.26 ] GPlayCli version via `gplaycli -v`
- [pip install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ (own) token. ] The authentication method: (own) credentials or (own) token.

502 Bad Gateway exception occurred when downloading with gplaycli today! ! !

**Comment by matlink** [comment]
See https://github.com/yeriomin/token-dispenser/issues/23

**Comment by LXQBer** [comment]
Is your proxy server abnormal?

**Comment by matlink** [comment]
Google is blocking my authentication for unknown reasons

**Comment by LXQBer** [comment]
Ok, thank you for your reply, I hope you can notify me after the recovery, thank you.

**Comment by alex9434** [comment]
I have exactly the same error.

**Comment by asharif1990** [comment]
+2 I got the same error.

**Comment by dilinger** [comment]
I'm hitting this as well. Subscribing here so I can update the Debian package once it's fixed.

**Comment by Rasamuel92** [comment]
Same here

**Comment by monsternian** [comment]
+1

**Comment by matlink** [comment]
Okay, I've put a new token-dispenser using this : https://github.com/matlink/python-token-dispenser.
It should be ok right now.

**Comment by davefalak** [comment]
where is the token-dispenser hosted?  https://matlink.fr/token is not available anymore?
