### ISSUE TITLE
Add app version to filename

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#23]

**Comment by matlink** [comment]
Can be tried on this branch https://github.com/matlink/gplaycli/tree/version-name

**Comment by matlink** [comment]
Was merged to master (https://github.com/matlink/gplaycli/commit/a2fc722cb4ca93458c7729f7bd60be60fad6fc9c) then removed (https://github.com/matlink/gplaycli/commit/769d770707f57245c67465cc5e148b5eebfb049b) but I can't remember why.

**Comment by zorun** [comment]
Could it be brought back?  It would be a useful feature!

**Comment by zorun** [comment]
Looking at the proposed code, the method to find other versions of the same package seems quite fragile (e.g. `filename.split('-')[1].split('.')[0]`).  Maybe this is why it was reverted?

**Comment by matlink** [comment]
Yes maybe.

**Comment by matlink** [comment]
Fixed in 3.27
