### ISSUE TITLE
AppendVersion is broken with own credentials

### ISSUE THREAD

**Issue by Apfelwurm** [matlink/gplaycli#232]
When calling the -av option the following error occurs:

`sudo gplaycli -d APPNAME -c test.conf -av                                                                                          
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gplaycli/gplaycli.py", line 724, in main
    cli.download(args.packages_to_download)
  File "/usr/local/lib/python3.7/dist-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gplaycli/gplaycli.py", line 252, in download
    filename = detail['docid']+ "-v." + detail['versionstring'] + ".apk"
KeyError: 'versionstring'
`

i did a bit of testing and found out that the datastructure might changed a bit. 
i could fix it by changing the line 253 of gplaycli.py from

`filename = "%s-v.%s.apk" % (detail['docId'], detail['versionString'])`

to

` filename = detail['docid']+ "-v." + detail['details']['appDetails']['versionString'] + ".apk"`

(the fix of #231 is here also applied)

- Kubuntu 19.10
- Versions 3.26 [Python3.7.5]
- installed via `pip install gplaycli`
- Authentication with Google account with app passwd in cleartext

**Comment by matlink** [comment]
Fixed in 3.27.
