### ISSUE TITLE
make gplaycli work with latest gpapi (0.4.4)

### ISSUE THREAD

**Issue by matt668** [matlink/gplaycli#234]
Latest gpapi has changed the structure of returned objects/dicts.

Search functionality no longer works along with other functionality such as download.

gplaycli installed from git clone
gpapi installed using "pip install gpapi==0.4.4"

using own credentials

**Comment by matt668** [comment]
#231

**Comment by matt668** [comment]
Created a pull request #235

**Comment by matlink** [comment]
Done in 3.27
