### ISSUE TITLE
install gplaycli.conf into /etc

### ISSUE THREAD

**Issue by blshkv** [matlink/gplaycli#242]
The current idea does not work for linux distro packaging.

If a regular user is installed it using ```app_manager install gplaycli```, the config file will be in ~/root folder (most probably). It is even worse in Pentoo Linux (and may be others), because we install it in a sandbox under regular user "portage", so the config file is getting installed into non-existing "home" folder which goes nowhere.

I suggest taking with are more common approach: install it into /etc folder by default. Each user can overwrite it with his own config if required.

**Comment by matlink** [comment]
There is a patch applied by the Debian package process (see debian/ directory) but it is quite hard to generalize for all distro.

**Comment by blshkv** [comment]
P.S. The software can still create whatever required during runtime in the home directory, or each user should be able to customise config in his local folder overriding the global settings.

**Comment by matlink** [comment]
The problem is that I need to distinguish whether the installation is running with --user or not (using pip).

**Comment by matlink** [comment]
That poses some issues:
- how to determine when to use `/etc` and when to use `~/`?
- `/etc` is probably not adapted for Windows and MacOS.

**Comment by enovella** [comment]
Any workaround for this issue?

```c
[INFO] GPlayCli version 3.27 [Python3.6.9] 
[INFO] Configuration file is None
[INFO] Device is bacon
[ERROR] Cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token/email/gsfid/bacon
[ERROR] Unknown error: Token-dispenser is unavailable due to IP blacklisted from Google

```

**Comment by matlink** [comment]
use your own credentials and disable token dispenser. And post in the 
correct issue please.

**Comment by matlink** [comment]
@blshkv I think it is should be required for the package manager to hanle the config file, otherwise it will be overwritten by the installation process. Distutils provides a way to install it depending on the installation permissions (system or user) but they are located at `/usr/local` and `~/.local`. When an update is release, `pip` overwrites the configuration file.

**Comment by blshkv** [comment]
Packet manager does handle it, if it is getting installed into a system dir.

**Comment by matlink** [comment]
So `/usr/local/etc/gplaycli/gplaycli.conf` looks good to you?

**Comment by matlink** [comment]
check the 'dev' branch, the building process (`make deb`) now install the config in `/etc`.

**Comment by blshkv** [comment]
I have reviewed the change, looks good. The code has been changed to the following:
```
data_files=[
			['etc/gplaycli', ['gplaycli.conf']],
		],
```
