### ISSUE TITLE
Download APK's for AMD/Intel? Installing Verizon Message+ for Anbox

### ISSUE THREAD

**Issue by EliterScripts** [matlink/gplaycli#243]
I am trying to get Verizon Message+ or "Verizon Messages" to run on my computer (running a 64-bit AMD processor). I am using Anbox. I noticed the blacklisting error, so I used the config to use my Google account. I downloaded "com.verizon.messaging.vzmsgs.apk" using your gplaycli, using this command: "gplaycli -c config.conf -d com.verizon.messaging.vzmsgs". I installed your gplaycli by using this: "pip3 install gplaycli --user"

Then, when I install your APK onto Anbox, I get this error:
```
$ adb install com.verizon.messaging.vzmsgs.apk
17936 KB/s (85843584 bytes in 4.673s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
I understand that this is because the APK for Verizon Messages is probably designed for ARM processors, since most phones run ARM processors. However, I wanted to see if Google Play store can also issue APK versions for other processors. If not, then I guess this is an open-and-shut issue.

- [ Ubuntu Desktop 16.04] Operating System (ie Ubuntu 16.04)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

- [ ] Python version when running `gplaycli` (should be 3+)
```
$ gplaycli -V
3.27 [Python3.5.2]
```
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ ] The authentication method: (own) credentials or (own) token.
Credentials, gmail/password I guess?

**Comment by matlink** [comment]
Yeah, it is in theory possible. I guess your CPU is an x86_64 arch. You should find an x86_64 android device and use its codename to download the file.

**Comment by EliterScripts** [comment]
![image](https://user-images.githubusercontent.com/17048113/75469587-801d1e80-594c-11ea-84c5-7f2956796bc5.png)
Alright, so this is what "Settings > About emulated device" looks like.

**Comment by EliterScripts** [comment]
Okay, so this is the error I got:
```
$ gplaycli -c config.conf -dc Nougat -d com.verizon.messaging.vzmsgs
usage: gplaycli [-h] [-V] [-v] [-s SEARCH] [-d AppID [AppID ...]] [-y]
                [-l FOLDER] [-P] [-av] [-a] [-F FILE] [-u FOLDER] [-f FOLDER]
                [-dc DEVICE_CODENAME] [-t] [-tu TOKEN_URL] [-ts TOKEN_STR]
                [-g GSF_ID] [-c CONF_FILE] [-p] [-L]
gplaycli: error: argument -dc/--device-codename: invalid choice: 'Nougat' (choose from 'alien_jolla_bionic', 'angler', 'aries', 'bacon', 'bbb100', 'BRAVIA_ATV2', 'bravo', 'bullhead', 'cloudbook', 'crackling', 'cwv88s', 'eeepad', 'foster', 'fp2', 'fresh', 'fs454', 'gemini', 'gtp7510', 'gts3llte', 'hammerhead', 'hero2lte', 'honami', 'JP-1601', 'K013_1', 'kenzo', 'm201', 'm3xx', 'maguro', 'mako', 'manta', 'nxtl09', 'oneplus3', 'pico', 'sailfish', 'shamu', 'sloane', 't00q', 'Tab_8_4C', 'walleye', 'wetekplay2')
```

**Comment by matlink** [comment]
Nougat is the version name of the android version you are using.
I know that the android emulator from Android Studio, which is running with x86_64 arch, can download and run apps from the play store. So it is possible, but I don't know which device they fake.

**Comment by EliterScripts** [comment]
It is Anbox, I don't believe it is Android Studio. https://anbox.io/ https://github.com/anbox/anbox They don't have the Play Store, that's why I had to get your tool to get the Verizon Messages app.

**Comment by matlink** [comment]
Yeah, I know. I'm just telling that it is possible since they do it in the official android emulator shipped with Android Studio.

**Comment by matlink** [comment]
BTW you should check https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html as it is probably easier to install play store in Anbox than changing ABI for downloaded apps.

**Comment by matlink** [comment]
Apparently, downloading with `-dc cloudbook` provides x86 dynamic libraries which should be runnable by your x86 anbox.

**Comment by matlink** [comment]
Apparently, this app is not available for x86-like abis: https://www.apkmirror.com/apk/verizon-vz/verizon-messages/verizon-messages-6-9-13-release/
