### ISSUE TITLE
how do I generate a token string ?

### ISSUE THREAD

**Issue by jacobhub** [matlink/gplaycli#245]
OS: windows 10 
Python 3.7.0
GPlayCli version 3.28
Installed via : git clone https://github.com/matlink/gplaycli && pip3 install ./gplaycli/
(own) credentials

Hi,
I am trying to use the cli with my own GSFID but this requires a "Token String" how do I generate that ( I want to use my own credentials and GSFID ) ?

**Comment by matlink** [comment]
There are two ways of authenticating: credentials or using token from token-dispenser. To select credentials, put `token=False` in the config file, and put your gmail address and password. That's it. The token and the GSFid will be retrieve automatically.

**Comment by jacobhub** [comment]
When I try just with credentials the download fails for **us.zoom.videomeetings** with : 'Item not found' error
