### ISSUE TITLE
unable to find/download an app

### ISSUE THREAD

**Issue by blshkv** [matlink/gplaycli#247]
https://play.google.com/store/apps/details?id=sg.gov.tech.bluetrace
app-misc/gplaycli-3.29
dev-python/matlink-gpapi-0.4.4.5
Python 3.6.10

```bash$ gplaycli -s TraceTogether```
returns 7 apps, but tracetogether

```bash$ gplaycli -d sg.gov.tech.bluetrace```
[ERROR] A few packages could not be downloaded :
sg.gov.tech.bluetrace
Item not found

**Comment by anupdey99** [comment]
https://play.google.com/store/apps/details?id=sg.gov.tech.bluetrace

**Comment by Gu1nness** [comment]
I guess it is because this app is geo-based restricted to Singapore.
I wanted to download it as well, but on my side, I can't get a token :/

**Comment by anupdey99** [comment]
https://apps.evozi.com/apk-downloader/?id=sg.gov.tech.bluetrace

**Comment by anupdey99** [comment]
You can download apk file and install on your phone but I think you will need singapore phone number to register.

**Comment by blshkv** [comment]
They have removed that strange restrictions.
