### ISSUE TITLE
https://matlink.fr/token 404 error

### ISSUE THREAD

**Issue by zjbthomas** [matlink/gplaycli#253]
Hi,

https://matlink.fr/token has 404: Not found error at 12/Apr/2020.

Could you please check the status of the server? Thank you.

Please provide those informations:

- [ ] Windows 10
- [ ] Python version: 3.5
- [ ] GPlayCli version: 3.24
- [ ] The way you installed `gplaycli`: `python3 -m pip install gplaycli`
- [ ] The authentication method: default token.

**Comment by matlink** [comment]
This link should not be directly accessed. It is used as a base for gplaycli, like "https://matlink.fr/token/email".
