### ISSUE TITLE
Unable to search or download official US Starbucks app

### ISSUE THREAD

**Issue by cwmke** [matlink/gplaycli#26]
Title says it all.  I've tried Raccoon as well and have been unable to search for or download with the id.  I have also tried generating new Android Ids and using the default credentials.   The id is com.starbucks.mobilecard.  Thanks for any help you can provide!

**Comment by msdos** [comment]
I've tried as well and the package can't be found.

**Comment by matlink** [comment]
Similar to https://github.com/matlink/gplaycli/issues/27
