### ISSUE TITLE
Installation doesn't work; cannot run; `ImportError: No module named androguard.core.bytecodes`

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [matlink/gplaycli#268]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [x] Operating System (ie Ubuntu 16.04): **Ubuntu 18.04**
- [x] Python version when running `gplaycli` (should be 3+) **3.6.9**
- [x] GPlayCli version via `gplaycli -v` **error: see traceback below**
- [x] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ... **see below**
- [x] The authentication method: (own) credentials or (own) token. **don't know what you're talking about**

----

Installation doesn't work:

I first tried:

    python3 -m pip install gplaycli

This said it worked, then produced the below error when I tried to run it. So then I did `sudo apt install gplaycli`, which had the same result (installation "worked" but it won't run).

```
$ gplaycli -v
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 28, in <module>
    from androguard.core.bytecodes import apk as androguard_apk  # Androguard
ImportError: No module named androguard.core.bytecodes
```

and

```
$ gplaycli -h
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 28, in <module>
    from androguard.core.bytecodes import apk as androguard_apk  # Androguard
ImportError: No module named androguard.core.bytecodes
```

**Comment by eighthave** [comment]
Did you try `python3 -m pip install androguard`?

**Comment by matlink** [comment]
Please try to update `gplaycli`:
`python3 -m pip install gplaycli --upgrade`
because it doesn't use `androguard` anymore, `pyaxmlparser` instead.
