### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#269]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [windows10 ] Operating System (ie Ubuntu 16.04)
- [python3+ ] Python version when running `gplaycli` (should be 3+)
- [3.29 ] GPlayCli version via `gplaycli -v`
- [pip install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ token ] The authentication method: (own) credentials or (own) token.

I encountered the problem of invalid url address of token again, and the status code returned was 502. How can I solve it?

**Comment by noctux** [comment]
First of all: Thank you for providing gplaycli and the service :)

I guess I'm hit by this as wel on two systems:

[Debian 10.5, Archlinux] Operating System (ie Ubuntu 16.04)
[ 3.7.3 and 3.8.5] Python version when running gplaycli (should be 3+)
[3.29] GPlayCli version via gplaycli -v
[git clone+pip and aur] The way you installed gplaycli: git clone, git clone and setup.py, pip install gplaycli, apt install gplaycli, ...
[ token; matlink.fr/token ] The authentication method: (own) credentials or (own) token.

The Archlinux installation is a clean installation of the latest release with a clean environment and the sample config file unmodified.

Config file:
```
[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
token=True
token_url=https://matlink.fr/token

[Cache]
token=~/.cache/gplaycli/token

[Locale]
locale=en_GB
timezone=CEST
```

Output of `gplaycli -s signal -vvv` (yeah, the search as such is not that useful, but it does not get that far)
```
[INFO] GPlayCli version 3.29 [Python3.8.5] 
[INFO] Configuration file is /home/noctux/.config/gplaycli/gplaycli.conf
[INFO] Device is bacon
[Errno 2] No such file or directory: '/home/noctux/.cache/gplaycli/token'
[INFO] Cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token
[ERROR] Cannot retrieve email address from token dispenser
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 651, in main
    cli.search(args.search, not args.paid)
  File "/usr/lib/python3.8/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 412, in connect
    self.retrieve_token()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 193, in retrieve_token
    raise ERRORS.TOKEN_DISPENSER_SERVER_ERROR
TypeError: exceptions must derive from BaseException
```

Wireshark tells me that an encrypted connection is negotiated with the Tokendispenser, but after that point, no data is received from the Server, until it closes the connection using `[FIN,ACK]`. I did not bother to use mitmproxy just yet, but I guess the token-dispenser server behind the reverseproxy is just down. @matlink: is `http://matlink.fr/token` expected to work at the moment (please excuse the explicit ping but I guess you are the only one who can answer that)?

Please ping me if you need any further information or I can be of assistance.

Thank you and best regards,
Simon

**Comment by matlink** [comment]
I guess that my token dispenser was down during that period.
Please answer this if it happens again.
