### ISSUE TITLE
Can't download some apks (like com.tomtom.speedcams.android.map), it exists when browsing, but can't download

### ISSUE THREAD

**Issue by msdos** [matlink/gplaycli#27]
It exists in the play store at https://play.google.com/store/apps/details?id=com.tomtom.speedcams.android.map but I can't download it.

```
gplaycli -d com.tomtom.speedcams.android.map
Error while downloading com.tomtom.speedcams.android.map : this package does not exist, try to search it via --search before
```

Maybe it's similar to https://github.com/matlink/gplaycli/issues/26. I'm using the official credentials.conf, other packages are fine.

**Comment by msdos** [comment]
This seems to be googleplay api related.

https://github.com/matlink/gplaycli/blob/609a45fb0994f815c8ef375921a0d61d402f0896/ext_libs/googleplay_api/googleplay.py#L256

When doing

> gplaycli -d com.spotify.music

> url = https://android.clients.google.com/market/download/Download?packageName=com.spotify.music&versionCode=12061610&ssl=1&token=AOTCm0Q-kAOt4uVfDRGp5Ldmr1ZqAjhZRUx20lSK_1fBVEafT_iTcNkdVwVLxF2fCEOw4XtpSWVGv67vFi21QvzJIompEUryHebSSjFx3kD7ZNY1qC-Rdgog_0WEa1bf9U8fMJ7t84I5qsoPExoJQiL_O5wN4jRCKo_O9t1FIdsXl-ZFjV7nn1G_9-n9OQpaGbfxHqCcBqlWVG6P3eX_URrJbZAhEQ&downloadId=8044160519998529321

> cookiename: "MarketDA" value: "06974654376624837863"

But when trying to download `com.tomtom.speedcams.android.map` url and `cookie` variables from [googleplay](https://github.com/matlink/gplaycli/blob/609a45fb0994f815c8ef375921a0d61d402f0896/ext_libs/googleplay_api/googleplay.py#L256) are empty.

**Comment by idgserpro** [comment]
Or maybe it's an error "not compatible with your device" for some reason and then it comes blank?

**Comment by matlink** [comment]
For reasons I don't know, some package cannot be downloaded via GplayCli. Moreover, experiences with other APK downloading softwares (search apk downloader on a search engine) show me that the package cannot be downloaded with any of these softwares. The bug seems to be linked to a library that all of these softwares are using, or linked to the Google API.

**Comment by msdos** [comment]
Some info about filtering: https://developer.android.com/google/play/filters.html

> **Filtering on the Google Play web site**
> When users browse the Google Play web site, they **can see all published applications**. The Google Play web site compares the application requirements to each of the user's registered devices for compatibility, though, and only allows them to install the application if it's compatible with their device.

Maybe this "library that all of these softwares are using" is missing something from filtering.

**Comment by matlink** [comment]
Indeed the device linked to the credentials I ship with gplaycli doesn't
seem compatible with certain applications. I had a look at how to
generate an android ID for another device but sadly didn't find
something conclusive.


Le 07/07/2016 à 16:09, msdos a écrit :
>
> Some info about filtering:
> https://developer.android.com/google/play/filters.html
>
>     *Filtering on the Google Play web site*
>     When users browse the Google Play web site, they *can see all
>     published applications*. The Google Play web site compares the
>     application requirements to each of the user's registered devices
>     for compatibility, though, and only allows them to install the
>     application if it's compatible with their device.
>
> Maybe this "library that all of these softwares are using" is missing
> something from filtering.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/matlink/gplaycli/issues/27#issuecomment-231088692>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEPnHoOIKaCbpUxSnOpEboiTvZ_ZMhsuks5qTQiegaJpZM4Ilz0K>.
>

-- 
Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by ChrisMcMStone** [comment]
Was a solution to this ever found? I'm getting the same problem even with some very standard apps like Dropbox.
