### ISSUE TITLE
Broken credentials based login

### ISSUE THREAD

**Issue by cherusk** [matlink/gplaycli#270]
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ ] Operating System (ie Ubuntu 16.04)
- [ ] Python version when running `gplaycli` (should be 3+)
- [ ] GPlayCli version via `gplaycli -v`
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [ ] The authentication method: (own) credentials or (own) token.

**Comment by nobicycle** [comment]
Same issue here.

$ python -V
Python 3.8.3

[user@tower Videos]$ uname -a
Linux tower 5.7.9-1-MANJARO #1 SMP PREEMPT Thu Jul 16 08:20:05 UTC 2020 x86_64 GNU/Linux

 gplaycli -v
[WARNING] No configuration file gplaycli.conf found at ['/home/user/Videos', '/home/user/.local/etc/gplaycli', '/usr/local/etc/gplaycli', '/etc/gplaycli'], using default values
[INFO] GPlayCli version 3.29 [Python3.8.3] 
[INFO] Configuration file is None
[INFO] Device is bacon

Install via package manager
pacman -S gplaycli


[INFO] Using credentials to connect to API
[INFO] Using plaintext password
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 651, in main
    cli.search(args.search, not args.paid)
  File "/usr/lib/python3.8/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 415, in connect
    ok, err = self.connect_credentials()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 448, in connect_credentials
    self.api.login(email=self.gmail_address, password=password)
  File "/usr/lib/python3.8/site-packages/gpapi/googleplay.py", line 236, in login
    raise SecurityCheckError("Security check is needed, try to visit "
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'

**Comment by Artiom-M** [comment]
Still broken with GPlayCli version 3.29 [Python3.9.5]

**Comment by matlink** [comment]
Please provide more informations with an exact traceback.

**Comment by nobicycle** [comment]
Hi, I checked if errors occurred as before:

```
$ python -V
Python 3.9.5
$ gplaycli -v
[INFO] GPlayCli version 3.29 [Python3.9.5] 
[INFO] Configuration file is /home/user/.local/etc/gplaycli/gplaycli.conf
[INFO] Device is bacon

```

Seems OK. Will update after testing download  functionality.

**Comment by Artiom-M** [comment]
Not working for me:
```
[INFO] GPlayCli version 3.29 [Python3.9.5] 
[INFO] Configuration file is /mnt/exchange/Android/gplaycli.conf
[INFO] Device is bacon
[INFO] Checking apks ...
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 646, in main
    cli.prepare_analyse_apks()
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 498, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, self.download_folder)
  File "/usr/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 415, in connect
    ok, err = self.connect_credentials()
  File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 448, in connect_credentials
    self.api.login(email=self.gmail_address, password=password)
  File "/usr/lib/python3.9/site-packages/gpapi/googleplay.py", line 262, in login
    raise SecurityCheckError("Security check is needed, try to visit "
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'
```

**Comment by matlink** [comment]
You should define an app password for your gmail account since it looks like you have 2FA enabled. 

Le 29 juin 2021 03:38:27 GMT+02:00, Artiom-M ***@***.***> a écrit :
>Not working for me:
>```
>[INFO] GPlayCli version 3.29 [Python3.9.5] 
>[INFO] Configuration file is /mnt/exchange/Android/gplaycli.conf
>[INFO] Device is bacon
>[INFO] Checking apks ...
>[INFO] Using credentials to connect to API
>[INFO] Using plaintext password
>Traceback (most recent call last):
>  File "/usr/bin/gplaycli", line 33, in <module>
>sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts',
>'gplaycli')())
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 646,
>in main
>    cli.prepare_analyse_apks()
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 498,
>in prepare_analyse_apks
>to_update = self.analyse_local_apks(list_of_apks, self.download_folder)
>File "/usr/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in
>check_connection
>    ok, err = self.connect()
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 415,
>in connect
>    ok, err = self.connect_credentials()
>File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 448,
>in connect_credentials
>    self.api.login(email=self.gmail_address, password=password)
>File "/usr/lib/python3.9/site-packages/gpapi/googleplay.py", line 262,
>in login
>    raise SecurityCheckError("Security check is needed, try to visit "
>gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to
>visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock,
>or setup an app-specific password'
>```
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/270#issuecomment-870160810

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Artiom-M** [comment]
I don't have 2FA enabled.

![image](https://user-images.githubusercontent.com/4058815/124591106-442e8d80-de9f-11eb-9640-adbf16b4c9ca.png)

**Comment by Artiom-M** [comment]
I also have this setting
![image](https://user-images.githubusercontent.com/4058815/124591662-e5b5df00-de9f-11eb-8ebf-00d8125a0dab.png)

**Comment by ahm750** [comment]
Anyone found a solution?

**Comment by cyberpion-yotam** [comment]
> Not working for me:
> 
> ```
> [INFO] GPlayCli version 3.29 [Python3.9.5] 
> [INFO] Configuration file is /mnt/exchange/Android/gplaycli.conf
> [INFO] Device is bacon
> [INFO] Checking apks ...
> [INFO] Using credentials to connect to API
> [INFO] Using plaintext password
> Traceback (most recent call last):
>   File "/usr/bin/gplaycli", line 33, in <module>
>     sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
>   File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 646, in main
>     cli.prepare_analyse_apks()
>   File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 498, in prepare_analyse_apks
>     to_update = self.analyse_local_apks(list_of_apks, self.download_folder)
>   File "/usr/lib/python3.9/site-packages/gplaycli/hooks.py", line 8, in check_connection
>     ok, err = self.connect()
>   File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 415, in connect
>     ok, err = self.connect_credentials()
>   File "/usr/lib/python3.9/site-packages/gplaycli/gplaycli.py", line 448, in connect_credentials
>     self.api.login(email=self.gmail_address, password=password)
>   File "/usr/lib/python3.9/site-packages/gpapi/googleplay.py", line 262, in login
>     raise SecurityCheckError("Security check is needed, try to visit "
> gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'
> ```
 
Same issue for me and I am using 2FA and an app password.
Going to the URL in the stacktrace doesn't solve the issue.
