### ISSUE TITLE
Error when trying to install gplaycli in python version 3.9?

### ISSUE THREAD

**Issue by sookyee** [matlink/gplaycli#274]
I'm using **Windows** and the **Python version I'm running is Python 3.9**.I ran the command **py -m pip install gplaycli** and I get 
Running setup.py install for xml...error
"ERROR: Command errored out with exit status 1".
![Error pic](https://user-images.githubusercontent.com/69225951/95806103-80322900-0d39-11eb-812a-c5063ac67f54.png)
![Error pic pt 2](https://user-images.githubusercontent.com/69225951/95806182-aeb00400-0d39-11eb-99de-8e74398d985b.png)
How do I install this module?

**Comment by matlink** [comment]
The error should appear a little higher.

**Comment by matlink** [comment]
It looks like you are using Microsoft Visual Studio, I don't know how it handles libraries but you should install `libxml2` in it.
