### ISSUE TITLE
when i use a new google account ,i can search but can't download app

### ISSUE THREAD

**Issue by thedoga** [matlink/gplaycli#28]
every app show 

> Error while downloading org.telenatura.pvgpslite : this package does not exist, try to search it via --search before
> A few packages could not be downloaded :
> org.telenatura.pvgpslite

while these pkg is exist in google play

**Comment by matlink** [comment]
every application you search shows this error?


Le 04/07/2016 à 10:42, thedoga a écrit :
>
> every app show
>
>     Error while downloading org.telenatura.pvgpslite : this package
>     does not exist, try to search it via --search before
>     A few packages could not be downloaded :
>     org.telenatura.pvgpslite
>
> while these pkg is exist in google play
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matlink/gplaycli/issues/28>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEPnHjbUZ8G-lrslcH3nZmuyiq_1pDp-ks5qSMeJgaJpZM4JEKjE>.
>

-- 
Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by msdos** [comment]
I just tested with default credentials from gplaycli and I can download this package. @thedoga can you try to download it using default credentials? From which country are you trying to download? How did you create this new google account?

**Comment by Julian2412** [comment]
Hi !
Same here, I can't connect with default credential and with my own, I can browse app but not download them.

**Comment by matlink** [comment]
Seems that the androidID is not correctly linked to the Google account you're using.
If not, re-open issue :)
