### ISSUE TITLE
[ERROR] Cannot retrieve email address from token dispenser

### ISSUE THREAD

**Issue by pitsi** [matlink/gplaycli#292]
Please provide those informations:

- Operating System: Debian testing/unstable x64
- Python version when running `gplaycli` (should be 3+): 3.9.11
- GPlayCli version via `gplaycli -v` : [INFO] GPlayCli version 3.29 [Python3.9.11]
- The way you installed `gplaycli`: apt-get install gplaycli
- The authentication method: token from the default server

Here is the full verbose output that shows all the above, e.g. when trying to download brave
```
$ gplaycli -v -d com.brave.browser
[INFO] GPlayCli version 3.29 [Python3.9.11] 
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
[Errno 2] No such file or directory: '/home/user/.cache/gplaycli/token'
[INFO] Cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token
[ERROR] Cannot retrieve email address from token dispenser
Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 666, in main
    cli.download(args.download)
  File "/usr/lib/python3/dist-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 413, in connect
    self.retrieve_token()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 194, in retrieve_token
    raise ERRORS.TOKEN_DISPENSER_SERVER_ERROR
TypeError: exceptions must derive from BaseException
```
Opening the token url in a browser results to a 502 error, so I assume this is the reason everything else fails. I do not have an own token, neither I want to use credentials.

**Comment by 89z** [comment]
> I do not have an own token, neither I want to use credentials.

Looks like youre out of luck then. A token dispenser is, and always has been a courtesy. The correct way to interact with Google Play is by using your email and password, same as if you were checking your email.

**Comment by pitsi** [comment]
But the app is supposed to download a token from the forementioned url by default, why should I bother for one? In this case, the instructions in the readme part no longer apply and should be removed.
If I wanted to use my google account credentails, which I know where to add, I would have done so. But I prefer not to use them on something that may cause google block my account. And that is not only gplaycli, but anything that has unofficial access to google's apis/services.

**Comment by pitsi** [comment]
Could this be related to #263?

**Comment by 89z** [comment]
> Although I do use windows (dual boot), I won't switch to it for a tool that I will use rarely.

who said that my tool requires Windows?

**Comment by pitsi** [comment]
Adding to the issue, I copied /etc/gplaycli/gplaycli.conf to my home directory, changed the dispenser url to `goolag.store:1337` which supposedly works, and launched gplay cli with `-c gplaycli.conf`.
But it gets stuck at the token retrieval forever
```
$ gplaycli -v -d com.brave.browser -c gplaycli.conf 
[INFO] GPlayCli version 3.29 [Python3.9.11] 
[INFO] Configuration file is ['gplaycli.conf']
[INFO] Device is bacon
[Errno 2] No such file or directory: '/home/user/.cache/gplaycli/token'
[INFO] Cache file does not exists or is corrupted
[INFO] Retrieving token ...
[INFO] Token URL is https://goolag.store:1337/
```
---edit
Any previous and following posts related to 89z's app were deleted and he is now blocked on my end.

**Comment by 89z** [comment]
> If so I would test it right away, but I am not going to build it myself.

Suit yourself, but you can literally download, build and run in less than one minute:

https://f002.backblazeb2.com/file/ql8mlh/googleplay.webm

**Comment by pitsi** [comment]
Since no one else is answering ontopic, let me continue this offtopic conversation. 

---edit
Nvm, I just noticed you deleted your previous messages. And I had just installed go on my system!
Please do not spam my issue report again with your app. If you do, you will leave me no other choise but to block you. 
Thank you and have a nice day,

**Comment by 89z** [comment]
> Please do not spam my issue report again with your app.

You are the one posting false information, such as:

> Although I do use windows (dual boot), I won't switch to it for a tool that I will use rarely.

When Go modules work with Windows, macOS or Linux, as can be easily seen:

https://go.dev/dl

> If you do, you will leave me no other choise but to block you.

I dont care. I have a tool that works. This tool does not work, hence why you posted the issue. If you dont want to spend the literally one minute it takes to build my tool, of course that is your choice. Good luck.

**Comment by pitsi** [comment]
Yea, I will not switch to windows for building it. I want a linux binary obviously. The provided windows binary can not run in linux natively. What does the go downloads page have to do with all that? I installed go with 'apt-get install golang'.
 
So, when compiling your app, go downloaded some stuff as seen here
```
go: downloading github.com/89z/format v1.21.5
go: downloading github.com/refraction-networking/utls v1.0.0
go: downloading google.golang.org/protobuf v1.27.1
go: downloading golang.org/x/crypto v0.0.0-20210817164053-32db794688a5
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
```
I assume that all of them can be installed via the package manager, so how I delete them and install them properly?

**Comment by pitsi** [comment]
Adding some insult to the injury. Leaving the token aside, I decided to use gplaycli with my own google credentials.
And it fails to authenticate, saying that my username and/or password may be incorrect!
```
$ gplaycli -v -d com.brave.browser -c gplaycli.conf 
[INFO] GPlayCli version 3.29 [Python3.9.12] 
[INFO] Configuration file is ['gplaycli.conf']
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[ERROR] Bad authentication, login or password incorrect ('server says: BadAuthentication')
```
Obviously, there is nothing wrong with the credentials. I tried them in a browser and they worked with zero issues.
And it makes no difference whether I enable access to less secure apps or not.

**Comment by pabs3** [comment]
I expect they require non-password authentication (probably OAuth2)
when logging in for non-browser situations and gplaycli uses passwds.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pitsi** [comment]
And how am I supposed to do that? There is no popup asking credentials so as to generate oauth password.
Does it work for you when using password in playtext? I have no one near me using debian, at the very least, so as to cross-test.

**Comment by pabs3** [comment]
I'm assuming gplaycli simply does not support OAuth yet, which is why
the login via browser works but via gplaycli does not.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pitsi** [comment]
So, with the token way not working because of server issues and the credentials way not working because of (probably) oauth issues, the app is practically useless?

**Comment by pabs3** [comment]
Until someone either implements OAuth or fixes the token server issues, yes.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by matlink** [comment]
I fixed some password-related issues on my token dispenser server. Apparently, application passwords had been removed by Google. Hope it helps.

**Comment by pabs3** [comment]
I just tried with the version of gplaycli in Debian, got this error:

$ gplaycli --log -d com.skype.raider
[ERROR] Multiple attempts to fetch anonymous token failed.
[ERROR] Try setting 'token=False' and adding Google credentials to gplaycli.conf
[ERROR] A few packages could not be downloaded :
com.skype.raider
'Error retrieving information from server. DF-DFERH-01'

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pitsi** [comment]
Do you also have the recommended packages installed, i.e. dummydroid, which pulls up A LOT of (mostly java related) dependencies, and frdoidserver, which pulls even more like android sdk?
On my end, the output is smaller with the --log parameter, compared with the verbose one. I get the same error like you with the stock settings that need a token
```
$ gplaycli --log -d com.skype.raider
[ERROR] Multiple attempts to fetch anonymous token failed.
[ERROR] Try setting 'token=False' and adding Google credentials to gplaycli.conf
[ERROR] A few packages could not be downloaded :
com.skype.raider
'Error retrieving information from server. DF-DFERH-01'
```
 and with the credentials way
```
$ gplaycli --log -d com.skype.raider -c gplaycli.conf 
[ERROR] Bad authentication, login or password incorrect ('server says: BadAuthentication')
```
So, there is no difference from what I have already mentioned.

---edit
I just saw @matlink 's post above for the change in the token server, so ignore the part that I said about the credentials way. Is the url still correct though?
`https://matlink.fr/token`

**Comment by pitsi** [comment]
I want to add that the output of `gplaycli -v -d something` is now different than before, e.g. 
```
$ gplaycli -v -d com.brave.browser
[INFO] GPlayCli version 3.29 [Python3.9.12] 
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
----------
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token
[INFO] Email: gplaycli5@gmail.com
[INFO] Token: aas_et/AKppINa0dg8bp3EiM-zYoXUzgzKVrglY41LTX1T-LsL4P1afvg-zCtv88BwRKCt3bHorP6ums6edKuqQFH-g_9j9TG6a4nEY6EsQ77NCI5_cacibhoTzVJ-R1t8j_7MUNsJKQZvVBHONImD4m9_6B0bHXll2dVN2HIl_pa9Xckb8mwU6lOV5rAZccVYirJoum9G6BxGKPmHEnwLZkvn3zzQ=
[INFO] GsfId: 3e440fdeeabd3f56
----------
[ERROR] Multiple attempts to fetch anonymous token failed.
[ERROR] Try setting 'token=False' and adding Google credentials to gplaycli.conf
[ERROR] A few packages could not be downloaded :
com.brave.browser
'Error retrieving information from server. DF-DFERH-01'
```
The lines in the middle of the output are repeated 4 times, each time with a different gsfid and token strings.

**Comment by pitsi** [comment]
And today I am getting a different output that looks like a mixed version of the above
```
$ gplaycli -v -d com.brave.browser
[INFO] GPlayCli version 3.29 [Python3.9.12] 
[INFO] Configuration file is /etc/gplaycli/gplaycli.conf
[INFO] Device is bacon
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
[INFO] Token has expired or is invalid. Retrieving a new one...
[INFO] Retrieving token ...
[INFO] Token URL is https://matlink.fr/token
[ERROR] Token dispenser server error: 502
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 429, in connect_token
    self.api.login(authSubToken=self.token, gsfId=int(self.gsfid, 16))
  File "/usr/lib/python3/dist-packages/gpapi/googleplay.py", line 250, in login
    self.search('drv')
  File "/usr/lib/python3/dist-packages/gpapi/googleplay.py", line 362, in search
    data = self.executeRequestApi2(path)
  File "/usr/lib/python3/dist-packages/gpapi/googleplay.py", line 336, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error while retrieving information from server. DF-DFERH-01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 33, in <module>
    sys.exit(load_entry_point('gplaycli==3.29', 'console_scripts', 'gplaycli')())
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 666, in main
    cli.download(args.download)
  File "/usr/lib/python3/dist-packages/gplaycli/hooks.py", line 8, in check_connection
    ok, err = self.connect()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 414, in connect
    return self.connect_token()
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 433, in connect_token
    self.retrieve_token(force_new=True)
  File "/usr/lib/python3/dist-packages/gplaycli/gplaycli.py", line 208, in retrieve_token
    raise ERRORS.TOKEN_DISPENSER_SERVER_ERROR
TypeError: exceptions must derive from BaseException
```
The process stops for some seconds at `[INFO] Token URL is https://matlink.fr/token` before continuing to the 502 error, so I assume that is the reason of the second part of the error.

**Comment by pitsi** [comment]
Is there ANY way to get ANY similar key from somewhere so as to get it working?
If the default key server did go online again for sometime those 3 weeks that I have opened the issue, then I have probably missed it.

**Comment by adtimizer** [comment]
@pitsi did you manage to come up with  a workaround?
would love to hear about it

**Comment by pitsi** [comment]
Sadly, no. In fact, I have not tried anything else for weeks now.
I tried again when I saw your post earlier, but the error is the same.

**Comment by adtimizer** [comment]
@89z in the spirit of collaboration between projects, maybe it will be good to share how you perform the login to google and fetch the token from there so someone can fix it on the python projects.
eventually we are all keen to make things work

**Comment by pitsi** [comment]
I am pretty sure he can not see your comment here because I blocked him for his attitude, spam and comment deletion.
And blocked users can not see or comment on issues. I just made sure his remaining comment is left there to prove my point.

**Comment by adtimizer** [comment]
@pitsi I wasn't aware of it.
my bad

**Comment by MolotovCherry** [comment]
This is sad. This app is not updated and doesn't even work with the latest python, let alone, can't login or use a token.

**Comment by ghost** [comment]
@MolotovCherry I have an alternate module and tool if it helps:

https://github.com/4cq2/googleplay

**Comment by pitsi** [comment]
@4cq2 
Aren't you 89z that I blocked last year for spamming? Thank you for keeping the same name on your project while creating a new user name. You are now blocked again.

---edit
Also, well done for deleting your old account. It also deleted that one message that I tried to keep here as a proof of your idiotic attitude.

**Comment by pitsi** [comment]
One day after my comment here, gplaycli was removed from the debian repo. 
https://tracker.debian.org/news/1431562/removed-329dfsg-4-from-unstable/

It is really sad to see the reasons, although they are all true :'(
