### ISSUE TITLE
Python 2.9 does not exist

### ISSUE THREAD

**Issue by show0k** [matlink/gplaycli#3]
"Works on GNU/Linux or Windows with pip and Python 2.9+"

**Comment by matlink** [comment]
Yes it's true, I meant 2.7. Was probably because I copy-pasted the
requirements from GooglePlayDownloader and had a mistake.

Le 16/08/2015 16:36, Théo Segonds a écrit :
>
> "Works on GNU/Linux or Windows with pip and Python 2.9+"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matlink/gplaycli/issues/3>.
>

-- 
Matlink - Sysadmin matlink.fr
