### ISSUE TITLE
Be able to choose architecture when downloading an app

### ISSUE THREAD

**Issue by 2tvenom** [matlink/gplaycli#31]
Hello, thx for library. gplaycli very helpful.

Where in code i can change device architecture for download arm or x86 apk?

Thank you

**Comment by matlink** [comment]
Well I don't know, maybe try to register an arm/x86 device androidID.
I don't think this is code-relative, but credentials-relative. Provide credentials and androidID for an arm device and the Play Store should provide the good architecture-compiled package.

**Comment by matlink** [comment]
Linked to #70
