### ISSUE TITLE
this package does not exist, try to search it via --search before

### ISSUE THREAD

**Issue by pi3rrot** [matlink/gplaycli#33]
Hello,
I have this error when I try to download an apk.

```
pierre@dedeimos ~ » gplaycli -s wirex         
Title                      Creator                         Size    Downloads     Last Update    AppID                                    Version  Rating  
Wirex. Carte de Bitcoin    Wirex                           21.7MB  10 000+      9 sept. 2016   com.wirex              

pierre@dedeimos ~ » gplaycli -d com.wirex 
Error while downloading com.wirex : this package does not exist, try to search it via --search before
A few packages could not be downloaded :
com.wirex
list index out of range
```

I have changed the credentials in .config/gplaycli/credentials.conf, and the searhc function find the ID.
Thanks for your job ;)

**Comment by halletienne** [comment]
Same here. I faked an android ID, but I am not sure this is linked...

**Comment by craftyguy** [comment]
I see this on quite a few packages, even after regenerating the android ID.

**Comment by matlink** [comment]
Duplicate ? https://github.com/matlink/gplaycli/issues/27

**Comment by craftyguy** [comment]
I don't believe it's a duplicate. There are some apps that gplaycli will either 1) refuse to find at all or 2) refuse to find when installing, but search works. This doesn't seem to be tied to the android ID since changing the android ID to devices that are supported by the app (e.g. MotoX 2014 or Nexus 5x) didn't have any effect.

**Comment by craftyguy** [comment]
Another interesting bit of info that might help is that I do not have this problem when using [Raccoon](http://www.onyxbits.de/raccoon), even with the same android ID/credentials. Raccoon is able to find and download these apps that gplaycli can't 'see'.

**Comment by matlink** [comment]
Interesting. Have you any appname in mind to give me for tests?

**Comment by craftyguy** [comment]
How about the maps.me in my earlier comment? Also, the android webview app seems to have problems too.

**Comment by matlink** [comment]
I'm able to download it with default credentials : 
```
$ ./gplaycli/gplaycli -pd com.mapswithme.maps.pro
[################################] 32356/32356 - 00:00:17
Download complete
```

**Comment by craftyguy** [comment]
Hmm, that one seems to be working now. Great!

However, there here's one that, when using the default creds, doesn't work even though it's found in the search:

```
$ grep 3d7 ~/.config/gplaycli/credentials.conf
android_ID=3d716411bf8bc802
$ gplaycli -s trimet                                
Title                           Creator                  Size     Downloads   Last Update   AppID                                     Version  Rating
TriMet Tickets                  TriMet                   20.7MB   100,000+    Sep 15, 2016  org.trimet.mt.mobiletickets               1085     3.19
TriMet Tracker Free             Joe Pinsonault           3.0MB    100,000+    Nov 3, 2016   com.beagleapps.android.trimettrackerfree  10       3.93
TriMet Go                       SomethingExplosive Apps  3.6MB    10,000+     Nov 17, 2016  com.something15525.trimetgo.trimet_go     73       4.26
Portland Bus 2 -TriMet tracker  Adrian Otero Vila        24.9MB   10,000+     Jul 23, 2015  ws.otero.adrian.portlandbus               2948     4.12
Transit Tracker - TriMet        hillman apps             3.7MB    5,000+      Sep 20, 2016  com.hillman.trimettransit                 107      3.68
Transit: Real-Time Transit App  Transit App, Inc.        11.2MB   1,000,000+  Nov 8, 2016   com.thetransitapp.droid                   1005400  4.23
PDX Transit Finder              Ryan Roemmich            113.6KB  50,000+     Jun 9, 2010   org.roemmich.pdxtransitfinder             13       4.39
Swiftly                         Swiftly, Inc.            8.9MB    1,000+      Sep 23, 2016  com.swyftapp.free                         117008   4.26
$ gplaycli -d org.trimet.mt.mobiletickets           
Error while downloading org.trimet.mt.mobiletickets : this package does not exist, try to search it via --search before
A few packages could not be downloaded :
org.trimet.mt.mobiletickets
list index out of range

```

**Comment by vimbrube** [comment]
so far i can't find tinychat (air.com.tinychat.mobile) or live.me (com.cmcm.live) apps with the search and i can't download them with the appID either (default config or otherwise).

**Comment by quydo** [comment]
the same for me

~ > gplaycli -c gplay.conf -pd com.facebook.shout
Error while downloading com.facebook.shout : this package does not exist, try to search it via --search before
A few packages could not be downloaded :
com.facebook.shout
list index out of range

**Comment by mohsennouri** [comment]
I have this problem too.
Even with several accounts(fake and real and default credential) I could not download most of useful apps.

**Comment by harsh1412** [comment]
I have the same issue..
Can't even download clash of clans..
Any temporary fix?

**Comment by deanott** [comment]
@harsh1412 what worked for me is just use a device with the lattest version of android :) should get most of the apps on the playstore that way. Might want to spin up a vm of the latest android device and take the android id from there 👍

**Comment by psycholyzern** [comment]
How do I generate an android ID? I used my phone's ID and it gave me an error. Now I am using ID that I took from internet.

**Comment by msdos** [comment]
> Might want to spin up a vm of the latest android device and take the android id from there

@deanott more examples on how to acomplish this? Did you download android sdk and set up the emulator? Where did you get the android id from there?

**Comment by NoMore201** [comment]
@msdos With recent versions of gplaycli and googleplay-api, the android id is generated from google servers and retrieved on first launch with credentials login (basically is the same thing as when you setup a new android device with a google account). In the code it's called `gsfId`. Notice that it will be different on every launch with credentials login.
