### ISSUE TITLE
Wrong return code when updated successfully

### ISSUE THREAD

**Issue by leegarrett** [matlink/gplaycli#36]
```
fdroid@fdroid:~$ /usr/bin/gplaycli -c /etc/gplaycli/credentials.conf -u /var/www/fdroid/repo
Using credentials.conf from current directory...
Everything is up to date !
fdroid@fdroid:~$ echo $?
1
```

I'd expect it to return 0 when everything is fine. This is important when using it in cron jobs or scripts, as a return code != 0 should be checked for abnormal runs.

**Comment by matlink** [comment]
Fixed https://github.com/matlink/gplaycli/commit/324163c808b6f017be8a61cc4c6493a182420b87

**Comment by leegarrett** [comment]
Thanks! Much appreciated!
