### ISSUE TITLE
Find a solution to embedded credentials.conf

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#38]
Providing default credentials result in some issues:

- anybody can change this account password
- this account could be used for bad purposes (spam, ...)

Current solutions we could take are: 

- Remove default credentials then add an easy way to create credentials and bind an androidID
- Make as difficult as possible for anyone except gplaycli maintainers to change the account password

We are open for propositions, if anyone has knowledge on such issues ...

**Comment by yeriomin** [comment]
Hello.
I wrote a [small web service](https://github.com/yeriomin/token-dispenser) which gives out auth tokens to anyone who asks. Like this:
http://tokendispenser-yeriomin.rhcloud.com/token/email/fdroidserver@gmail.com
http://tokendispenser-yeriomin.rhcloud.com/token-ac2dm/email/fdroidserver@gmail.com

It has been successfully used for a couple of weeks in my [Play Store alternative android app](https://github.com/yeriomin/YalpStore). It stores email-password pairs in a mongodb storage and generates new auth tokens on request. Right now it is deployed on RedHat OpenShift, but can be deployed anywhere.

**Comment by matlink** [comment]
Well, I'll need an explanation on how it works, since it does not seem to require a password. Is the fdroidserver@gmail.com account configured in your `tokendispenser` instance?

**Comment by yeriomin** [comment]
It stores email-password pairs and asks Google to create a token with a request to https://android.clients.google.com/auth.

I've taken email and password from your credentials.conf and put them into the tokendispenser's db. How you do it is up to you. OpenShift has an option to install rockmongo, so I'm using that. I considered adding a PUT method protected by basic http auth to tokendispenser, but it seems an overkill at this point.

**Comment by matlink** [comment]
Alright, very nice. 
How do I use the token? Should it replace the password, or should I modify my code to use a token-way authentication?

**Comment by yeriomin** [comment]
Instead of
`api.login(self.config["gmail_address"], self.config["gmail_password"], None)`
Use
`api.login(None, None, token_from_token_dispenser)`

...i think. Didn't try it.

**Comment by matlink** [comment]
Works like a charm. 
I'll need to push it now :)

**Comment by matlink** [comment]
Fixed by https://github.com/matlink/gplaycli/commit/562b53f60a6f414d9985e6a4c6246c9a0ee266d7
