### ISSUE TITLE
No debian package for 0.2 release?

### ISSUE THREAD

**Issue by losuler** [matlink/gplaycli#39]
I was just wondering what the reason was for not including it with the latest release.

**Comment by matlink** [comment]
Does 0.2 exist?

**Comment by losuler** [comment]
Isn't this it, https://github.com/matlink/gplaycli/releases/tag/0.2 ?

**Comment by matlink** [comment]
Looks like I messed up with tags version numbers ...
-- 
Matlink - sysadmin Matlink.fr
