### ISSUE TITLE
Filename not updated

### ISSUE THREAD

**Issue by dalb8** [matlink/gplaycli#4]
When running updates the new apk is downloaded but it gets the file name of the previous apk. e.g.

```
Analyzing com.comuto
The following applications will be updated :
com_comuto-275.apk Version : 275 -> 280

Do you agree?
y/n ?y
Downloading ...
1/1 com.comuto
Updated: com.comuto

xxx@xxx:~/srclib/gplaycli$ ls
com_comuto-275.apk  credentials.conf  ext_libs  gplaycli.py  __init__.py  LICENSE.md  README.md  requirements.txt
```

**Comment by matlink** [comment]
The thing is that some other softwares (for example FDroid) rely on the 
filename to check if the apk has changes since the last time. If instead 
I rename the apk when it updates, these softwares could believe that one 
apk is missing and another one has appeared, but might not be able to 
make the link between these events.

I'm looking for a more reliable solution that wouldn't disrupt the 
compatibility with any 3rd software, and also could help you to get the 
number version in the apk filename.

What is the main issue that pushes you to ask for rename it after update ?

Furthermore, I strongly think it's a bad behaviour to have the version 
number in the apk filename.

**Comment by dalb8** [comment]
Well, I maintained the f-droid.org repo at one point and came to know the system very well, so it's just that I am disturbed when it is tweaked in such a way. However, like you said, there isn't any real need to have the version code in there; in fact only when fdroidserver builds apks from source are they renamed in this way. Raccoon also has version code in file names (but unlike fdroidserver uses underscores and hyphens). It is simply a way to avoid collisions and to help people find a particular version when using adb install. If you are to continue with keeping one version only of each app then you don't need the version code.

BTW, at one point, fdroidserver was able to check Google Play for new apks by asking for the version code but when the site was revamped it was no longer possible to tell what the version code was without downloading an apk. Then there was $fdroid checkupdates --gplay which checked against __version name__ but that no longer works in master branch. But it remains useful to check Google Play, even when one builds apks from source, for situations when the source code is unreliable e.g. when the source repo has moved or the licence has changed.


-------- Message d'origine --------
De : Matlink <notifications@github.com>
Envoyé: 19 août 2015 14:13:16 UTC+01:00
À : matlink/gplaycli <gplaycli@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [gplaycli] Filename not updated (#4)

The thing is that some other softwares (for example FDroid) rely on the 
filename to check if the apk has changes since the last time. If instead 
I rename the apk when it updates, these softwares could believe that one 
apk is missing and another one has appeared, but might not be able to 
make the link between these events.

I'm looking for a more reliable solution that wouldn't disrupt the 
compatibility with any 3rd software, and also could help you to get the 
number version in the apk filename.

What is the main issue that pushes you to ask for rename it after update ?

Furthermore, I strongly think it's a bad behaviour to have the version 
number in the apk filename.

Le 19/08/2015 14:46, dalb8 a écrit :
>
> When running updates the new apk is downloaded but it gets the file 
> name of the previous apk. e.g.
>
> |Analyzing com.comuto
> The following applications will be updated :
> com_comuto-275.apk Version : 275 -> 280
>
> Do you agree?
> y/n ?y
> Downloading ...
> 1/1 com.comuto
> Updated: com.comuto
>
> xxx@xxx:~/srclib/gplaycli$ ls
> com_comuto-275.apk  credentials.conf  ext_libs  gplaycli.py  __init__.py  LICENSE.md  README.md  requirements.txt
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/matlink/gplaycli/issues/4>.
>



---

**Comment by dalb8** [comment]
Excuse me, I rewrote the last comment extensively. Please see the revised version.

**Comment by matlink** [comment]
Would you like to have some kind of argument (like `--update-filename`) to let GPlayCli being able to change filenames ?

**Comment by dalb8** [comment]
Are you planning on letting gplaycli keep more than one APK per app? If so, then you need an identifying element in the filename; the version code or else you could have the config set the number of APKs to keep: say 3, then append 1, 2 or 3 to the applicationID in the filename. If not, then you don't need the version code in the filename at all. The behaviour at the moment only confuses the repo maintainer a little and not the user of the f-droid client, so it doesn't bother me so much as to desire an extra flag.

**Comment by matlink** [comment]
Why have you got the version number of the apk in the filename ?

**Comment by dalb8** [comment]
Oh I'm so sorry for the confusion. I must have copied the APK from a Raccoon archive, run gplaycli -u and forgot about the original APK. So perhaps this issue should be renamed to consider standardization of filenames.

**Comment by matlink** [comment]
Ok so to be clear and simple : you want GPlayCli to rename files when 
name changes or also keep the old one ?

**Comment by dalb8** [comment]
Perhaps gplaycli should rename the file from com_comuto-31.apk to com.comuto.apk when ./gplaycli.py -u is run?

Or perhaps create a special flag to standardize filenames?

It's not a big problem really because filenames are not displayed in the F-Droid client. F-Droid client will think that the app has just been added to the repo no matter what name the file has, AFAIK.

**Comment by matlink** [comment]
Well in fact, GPlayCli downloads apks named with their package name. For example, Mozilla Firefox is named org.mozilla.firefox.apk. Moreover, GPlayCli is not supposed to rename files because it could disturb some users.
