### ISSUE TITLE
Cannot login to Google play

### ISSUE THREAD

**Issue by noinlijin** [matlink/gplaycli#42]
![image](https://cloud.githubusercontent.com/assets/3073370/21383205/8a44daac-c79f-11e6-87a6-50cd65f84111.png)

**Comment by losuler** [comment]
I tested this myself just to see and that app downloaded fine for me. Are you using the default credentials?

**Comment by noinlijin** [comment]
no I use other credentials, in different IP it will error like cannot login, but in android_id's device IP , it work well

**Comment by matlink** [comment]
Can you check https://github.com/matlink/gplaycli/issues/47?
