### ISSUE TITLE
Cannot login to GooglePlay ( server says: NeedsBrowser )

### ISSUE THREAD

**Issue by yourshell** [matlink/gplaycli#45]
i used this app long time,

teday,i download an app by it, but it is say:

 downCannot login to GooglePlay ( server says: NeedsBrowser )

how to change it?

**Comment by matlink** [comment]
Credentials have changed. Pull and try ;)

Le 16 février 2017 06:30:12 GMT+01:00, yourshell <notifications@github.com> a écrit :
>i used this app long time,
>
>teday,i download an app by it, but it is say:
>
> downCannot login to GooglePlay ( server says: NeedsBrowser )
>
>how to change it?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/45

-- 
Matlink - sysadmin Matlink.fr

**Comment by yourshell** [comment]
ok,its works

**Comment by matlink** [comment]
Are you using the 'pip' version or the 'github' version?

**Comment by yourshell** [comment]
pip and github , installed on different VPS
test the WWW via openshift ，app.yourshell.info

**Comment by BattleMage** [comment]
I have the same problem. I first installed the pip version, after I got this message, I uninstalled the pip version and compiled from github master branch, but it's the same. Verbose flag adds no more output, it's aways just ``Cannot login to GooglePlay ( server says: NeedsBrowser )``

**Comment by yourshell** [comment]
I think it is GOOGLE account security strategy,
https://support.google.com/accounts/answer/6010255?hl=en

https://myaccount.google.com/security?utm_source=OGB&pli=1#signin
