### ISSUE TITLE
credentials broken

### ISSUE THREAD

**Issue by vn971** [matlink/gplaycli#47]
Credentials got broken again. It should be fixable, right?

> Cannot login to GooglePlay ( server says: BadAuthentication )

Thank you

**Comment by vn971** [comment]
* EDIT ^

**Comment by mrjk990** [comment]
same issue :(

**Comment by philipphager** [comment]
same issue here

**Comment by mrjk990** [comment]
issue solved to me after change account password 
go to this [link ](https://accounts.google.com/DisplayUnlockCaptcha)and click continue

**Comment by philipphager** [comment]
I made it work by using my own account and temporarily disabling the two-factor authentication.

**Comment by mrjk990** [comment]
good news , pls test download this app com.supercell.boombeach work for u or not ?
`gplaycli -d com.supercell.boombeac`

**Comment by philipphager** [comment]
Yes it works for me, but I myself have got some problems downloading free apps. I think it depends on your store language and the device id you use in the credentials.conf, if your device is compatible with it.

**Comment by mrjk990** [comment]
yeh, can you give to me device id to test it ? i use default device id

**Comment by philipphager** [comment]
Sorry, that's the one of my private phone and it is tied to my Google account. It won't work for you. But if you got an Android phone yourself with the account used in the credentials.conf, you can retrieve your device's id easily i.e. with [this app](https://play.google.com/store/apps/details?id=com.feaws.deviceid&hl=de). Use the GSF ID and it should work.

**Comment by matlink** [comment]
I've pushed a new version of gplaycli, now using Token if you want (check the credentials.conf file).
Nobody will be able to change the new account password. I can't recover the last account for now, but well it don't care much about it.

**Comment by vn971** [comment]
Thanks a lot!
