### ISSUE TITLE
Some cryptography issue in ubuntu

### ISSUE THREAD

**Issue by harsh1412** [matlink/gplaycli#52]
![capture](https://cloud.githubusercontent.com/assets/20555951/24840664/9a0f928e-1d8e-11e7-8b1e-f1f0dfa3dfc3.PNG)
I tried installing the cryptography but it shows it already have this in the system..
I am really stuck here >.<

**Comment by harsh1412** [comment]
Installed a bunch of python library files and got it working..

**Comment by matlink** [comment]
Which Ubuntu version are you using?

**Comment by harsh1412** [comment]
@matlink Ubuntu 16,
Anyways got it working but now i can't download some packages, Like Clash of clans, etc
Can you tell me a temporary fix for that?
And what about Obb files?
