### ISSUE TITLE
Download Complete - No App downloaded

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#55]
Hi, I'm using gmail credentials in the credentials conf file and it shows download complete but apk didn't download. Please help.

**Comment by matlink** [comment]
Can you try `gplaycli -pd org.mozilla.firefox -v` and put the result here, please.

**Comment by christypriory** [comment]
`gplaycli -pd org.mozilla.firefox -v 
Using token to connect to API
Download complete
`

**Comment by matlink** [comment]
Weird. How did you installed gplaycli?

**Comment by christypriory** [comment]
I did git clone. App download with gmail creds was working fine till last month. i can still get it to work with token dispenser.

**Comment by matlink** [comment]
Well here you seem to be using the token authentication instead of credentials authentication

**Comment by christypriory** [comment]
I'm not sure why its showing like that my token is still false and even i tried -c credentials.conf and still the same.

**Comment by matlink** [comment]
Could you remove lines concerning token in credentials.conf and try again?

**Comment by christypriory** [comment]
wow, that worked.

`gplaycli -c credentials.conf -pd org.mozilla.firefox -v 
Using credentials to connect to API
1/1 org.mozilla.firefox
[################################] 37636/37636 - 00:00:03
Download complete
`

**Comment by matlink** [comment]
Well I'll need to fix it then.

**Comment by christypriory** [comment]
Sure. Thanks a lot.

**Comment by matlink** [comment]
Fixed by fe6f6332f3f3e732ab76fcecb7f46fd2907039d9
