### ISSUE TITLE
Feature request: Logs

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#56]
Hi, I will be very helpful if there is a logging option

save logs that contains the list of package names for the cases beow

- apps_downloaded_log.txt: Apps downloaded.
- apps_failed_log.txt: Apps failed. (because of too many connection for token or sometimes when cant login to google play: bad auth)
- apps_not_available_log.txt: Paid apps or limited to specific country.

**Comment by matlink** [comment]
Implemented in https://github.com/matlink/gplaycli/commit/80d4b864fb8ec7d8168e4b9d033aa32ead3702c1

**Comment by matlink** [comment]
18922dab051a8df6df61febbb8fe7e79705e7786 fixes a little bug

**Comment by christypriory** [comment]
Thanks a lot.
