### ISSUE TITLE
Download game data file (.obb)

### ISSUE THREAD

**Issue by Attect** [matlink/gplaycli#6]
Does it can be use to  download game data file (.obb)?
obb file usually located at /sdcard/Android/obb/<package>
Some games have 2 file : docV2->details->appDetails->file
Just like: https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA8HM
index 0:app's apk file(.apk)
index 1:game's data file(.obb)

I read the code and use Fiddler4 to find the API to download the data file,I try to change some code to try downloading data file but it failed.

**Comment by matlink** [comment]
I can't locate where you see that table with index 0 as the apk and index 1 as the game data file ?

**Comment by Attect** [comment]
I'm so sorry .I forgot tell you I print message.payload.detailsResponse as JSON.
code:print demjson.encode(protobuf_json.pb2json(message.payload.detailsResponse)) at googleplay.py ->GooglePlayApi->deatails

print message.payload.detailsResponse on console:
.........
uploadDate: "2015\345\271\2648\346\234\21012\346\227\245"
      file {
        fileType: 0
        versionCode: 20029
        size: 39655822
      }
      file {
        fileType: 1
        versionCode: 20029
        size: 1546013200
      }
      appType: "GAME"
    }
  }
  aggregateRating {
    type: 2
    starRating: 4.50587415695
    ratingsCount: 4373134
    oneStarRatings: 257305
    twoStarRatings: 95932
    threeStarRatings: 184984
    fourStarRatings: 473892
    fiveStarRatings: 3361020
    commentCount: 1273158
  }
.......
There are 2 file{}

**Comment by matlink** [comment]
Sounds hard, I can't get the URL of that obb file, the only info I have is that there is 2 files in this app and their weights.

**Comment by Attect** [comment]
Thanks ,I will try to download it by other way.
Finally,can you add an argument :print app's information (formated,JSON/XML) and exit?

**Comment by matlink** [comment]
What for ? To tell that the apk has a .obb file that needs to be downloaded ?

**Comment by Attect** [comment]
Other projects can  parser the app information easy.

**Comment by portablesoft** [comment]
This Firefox extension could download the .obb file of an app:

https://addons.mozilla.org/en-US/firefox/addon/apk-downloader/

Could you find any idea on the obb file download? Thanks.

**Comment by matlink** [comment]
Follow https://github.com/NoMore201/googleplay-api/issues/6

**Comment by archon810** [comment]
@matlink Can you please detail the .obb downloading capabilities added by https://github.com/matlink/gplaycli/releases/tag/3.5?

Specifically, is there a flag to enable .obb downloading so we can select whether obb is wanted or not per query? For example, I don't want obb downloads unless I ask for them, only APKs, and obb could be several gigabytes in size.

**Comment by matlink** [comment]
There is no flag. gplaycli always downloads obb files.
I'll add a flag to enable download of obb files, otherwise it will be disable by default.

**Comment by archon810** [comment]
Thank you, that's the right solution here.

**Comment by matlink** [comment]
Implemented https://github.com/matlink/gplaycli/tree/3.5
