### ISSUE TITLE
Credentials path with virtualenv

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#61]
When installing in a virtualenv, credentials are installed in this virtualenv, in a quite weird location (lib/python2.7/home/matlink/.config/gplaycli/credentials.conf)

**Comment by eighthave** [comment]
seems like using some of the standard path variables like `sys.prefix` and the XDG variables: https://askubuntu.com/questions/457047/how-can-i-get-the-xdg-default-user-directories-from-python
