### ISSUE TITLE
sometimes get error server says: BadAuthentication

### ISSUE THREAD

**Issue by jr3074** [matlink/gplaycli#62]
hello,
when i use it, sometimes i got (server says: BadAuthentication) error.
I didn't use token,
please help to avoid badAuth

thanks,,

**Comment by matlink** [comment]
Sometimes it works?

**Comment by jr3074** [comment]
yes, sometimes it works,
but sometimes it shows error badauth, so i have to try a few times until the error gone...
i got this problem since this week and never before, usually i use password for apps "16char", i think this is the problem, but after try my current password still got the problem..
i have tried displaycaptcha from previewsthread, change passwd, still got the problem, maybe there is new method to login to google?

**Comment by matlink** [comment]
which credentials do you use?

**Comment by jr3074** [comment]
my own user-password with my device id

**Comment by matlink** [comment]
Hum yes, looks like credentials authentication does not work anymore. I'll have to dig into this.

**Comment by jr3074** [comment]
sometimes i can login and it works, did you have same problem? or only on my side which have this problem?

**Comment by matlink** [comment]
I've got the same issue. Sometimes I can connect, sometimes I can't. 
It's maybe because those credentials are use too often in a short time.
Are your credentials use anywhere else?

**Comment by jr3074** [comment]
yes i use it on my daily android device,

**Comment by matlink** [comment]
When I said anywhere else I meant at the same time that you're using gplaycli

**Comment by jr3074** [comment]
i only use gplaycli (from usa server), but at the same time i logged in on my current device (indonesia)

**Comment by ford--prefect** [comment]
I can confirm this from a german server, but it happens always, even with a new google account. The google account is only used for this purpose and only used for debug logins with my home machine.
Finding the cause and fixing the issue would be bagus banget (good).

**Comment by peterstory** [comment]
I'm seeing this problem as well. Interestingly enough, I encounter the same problem when using Raccoon version 3.7. Perhaps Google did something that is causing this problem.

**Comment by peterstory** [comment]
Using "token" authentication fixes the problem. But I'd prefer to be able to use my own credentials.

**Comment by peterstory** [comment]
I wonder if this is related:
https://github.com/yeriomin/token-dispenser/issues/2

**Comment by matlink** [comment]
Yes, I fixed token dispenser by retrying another account until 5 times. 
There is probably something to fix for a better solution.

**Comment by jr3074** [comment]
did you have solution for this problem?

**Comment by rchatterjee** [comment]
Can I create token for my email accounts? I need to download a lot of apks, and I don't want to overload your credentials. If there is a way to setup the token with own credentials that will be great. I tried using the google username and password, it does not work.

**Comment by matlink** [comment]
@rchatterjee something related to developers in your Google account settings could allow you to generate a token for a given app

**Comment by Mutt-Huyh** [comment]
This change seems to solve the "BadAuthentication" problem

https://github.com/onyxbits/raccoon4/commit/0c2196be000bed01c8c0c8c72e955355aa9bf80d

**Comment by archon810** [comment]
Yes, it switches Raccoon from Passwd to EncryptedPasswd, which is what token dispenser already did here https://github.com/yeriomin/play-store-api/commit/817d0268be37ff2ca71f3b973f9441df10245457.

**Comment by subtletech** [comment]
I've implemented the password encryption also in ruby in case anyone needs it: https://github.com/subtletech/google_play_store_password_encrypter

**Comment by matlink** [comment]
Thanks I'll probably adapt it in python.

**Comment by matlink** [comment]
@subtletech I'm interested to know where you find the documentation for that kind of encryption?

**Comment by peterstory** [comment]
In terms of discovering what encryption Android uses, I think it's a matter of reverse-engineering Android: http://blog.onyxbits.de/lets-talk-about-raccoon-v4-1-1-631/

**Comment by matlink** [comment]
Well, I tried to port @subtletech 's ruby code into a python one there https://github.com/matlink/gplaycli/commit/74362170d82ade56e6d63e022e5aed2f80f1cceb
Still unsuccessful, can't figure out where I'm wrong.

**Comment by archon810** [comment]
FWIW, everything is still working on my end, using our own account and our own token dispenser. So it's not broken universally for everyone, something with your account/setup.

**Comment by matlink** [comment]
Well I'm talking about when you login without tokendispenser but with your own credentials, aka setting email and password in gplaycli.conf
