### ISSUE TITLE
Feature request: Load file & Retry option

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#65]
**Load list of packages from a text file**
It will be very helpful if there is an option to load a list of package names from a text file (each line) and then download. If the logging option is enabled along with the loaded list then after completing the task the user will get the log for list of packages downloaded, failed and not_available.

**Retry option**
If the download shows "Too many connection for token" or "Cant login to google play: bad auth" then it will be helpful to retry 3 times max.

**Comment by matlink** [comment]
For the retry option, there is already something similar with tokendispenser : it tries again 5 times maximum.
On the way for load from file.

**Comment by matlink** [comment]
Check loadfromfileandretry branch

**Comment by christypriory** [comment]
I have loaded and tested 500 apps looks good. Thanks.

Sometimes i can see the error `Token dispenser auth error, probably too many connections` before starting the download. But on executing again as soon as it starts downloading, i have not seen any issues till it completes.

**Comment by jr3074** [comment]
bath auth issue, i think google changed their method to login to google account, maybe
