### ISSUE TITLE
Error Message shows "Download complete"

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#66]
I can see "Download complete" in the error message  like

`root@debian:~# gplaycli -d com.abcd`
`Error while downloading com.abcd : this package does not exist, try to search it via --search before`
`Download complete`
`root@debian:~# `

**Comment by jr3074** [comment]
the app isn't available for your device id or your country, you can try to change your device id, use your real device id from your phone

**Comment by christypriory** [comment]
@matlink It will be very helpful to show Download failed for this case.

**Comment by matlink** [comment]
Fixed by e8431be3b8dddc380fd4b6126eed966196f8bc75
