### ISSUE TITLE
Login error due to possible throttling at Google's end

### ISSUE THREAD

**Issue by rehmatworks** [matlink/gplaycli#73]
Seems like Google has started throttling the app installation requests and this affects all APK downloaders including gplaycli. If we try downloading an app without waiting for a minute after the last download, a login error is presented. Is there any workaround for this? Please note that this isn't an issue related to the account login credentials. Any input is highly appreciated.

**Comment by jr3074** [comment]
got an issue bad authentification

**Comment by archon810** [comment]
Same issue here - tons of sporadic BadAuthError errors using our own accounts.

**Comment by matlink** [comment]
Well ... We need to investigate this. 
Do you know if the play store app on android needs to wait 1 min between downloads?

**Comment by archon810** [comment]
Raccoon has been complaining about this recently quite a bit.

http://blog.onyxbits.de/lets-talk-about-raccoon-v4-1-1-631/
http://blog.onyxbits.de/and-google-broke-raccoon-again-2-625/
http://blog.onyxbits.de/catch-22-when-raccoon-suddenly-stops-working-622/
http://blog.onyxbits.de/looks-like-google-changed-the-play-protocol-again-614/

**Comment by rehmatworks** [comment]
@matlink Hi, thanks for your kind reply. In Google Play app, I can't notice this but I've verified this on my server. I hope you will bring us some sort of solution.

**Comment by matlink** [comment]
Is the issue reproducible with the token way of authentication?

**Comment by archon810** [comment]
@matlink I'm not using tokens, need to look into it.

**Comment by archon810** [comment]
@matlink Have a look at this: https://github.com/yeriomin/token-dispenser/commit/5b9779a11a0d5e7099bae879128727fe1279b11f. Looks like the dev there @yeriomin figured out what was going on with auth errors.

**Comment by rehmatworks** [comment]
@matlink The issue doesn't come up with your token solution but the main issue here is that I'm using a modified version of gplaycli that is capable of download OBB data as well and I can't use the token auth wit it.

**Comment by matlink** [comment]
@archon810 yes I saw it. However, I'll need to dig into it very deeply to understand how Google API works.
@rehmatworks well okay. Feel free to pull request your OBB capable version :D

**Comment by archon810** [comment]
+1 for the obb code to be PRed.

**Comment by rehmatworks** [comment]
@matlink @archon810 It requires some modifications in GooglePlayDownloader as well so I don't feel that a merge will do any big help. Users will be ending up installing a broken script :)

**Comment by detrout** [comment]
Is it working for others now? I was pretty sure I was experiencing this authentication problem, and gplaycli -s is working for me now now.
