### ISSUE TITLE
Bug: Shows Download Complete when Download Failed

### ISSUE THREAD

**Issue by christypriory** [matlink/gplaycli#75]
Download failed and token missing but shows Download Complete

`GPlayCli version 0.2.5 `
`Configuration file is /root/.config/gplaycli/credentials.conf `
`Retrieving token ... `
`Token:  `
`Using token to connect to API` 
`Download complete`

**Comment by matlink** [comment]
Well first, don't run gplaycli With root privileges.
And second, I'm gonna put this case in failure, but we'll need to figure out why your token is empty. Are you able to reproduce?
