### ISSUE TITLE
The search option throws error when no number given, and when number is larger than results

### ISSUE THREAD

**Issue by ryan-yap** [matlink/gplaycli#77]
I am using Ubuntu 16.04, python 2.7, GPlayCli version 0.2.5. Installed it using pip install gplaycli. I was using the GPlayCli 0.1.2 and the search was returning the correct result. After I upgraded it to 0.2.5, the issue came. For example, I was search for YogaVPN (gplaycli -s "com.yogavpn") the search returns something else to me. However, when I checked it on the Play Store, I was still able to find the app.

**Comment by matlink** [comment]
I've reverted a commit (PR https://github.com/matlink/gplaycli/pull/78) which fixed some issue with the `-n` option. However, it introduced other bugs that we didn't see at first

**Comment by ryan-yap** [comment]
yeap, that fixes the problem. Thank you very much!
