### ISSUE TITLE
Download paid apps

### ISSUE THREAD

**Issue by matlink** [matlink/gplaycli#8]

**Comment by vetetix** [comment]
Bonjour, où en est cette fonctionnalité ?
J'imagine qu'il y a beaucoup d'utilisateurs de gplaycli qui seraient intéressés.

**Comment by matlink** [comment]
Aucune progression. Je n'ai pas pris le temps de regarder comment faire, je ne sais même pas si c'est possible.

**Comment by vetetix** [comment]
Je peux confirmer que c'est possible. J'ai téléchargé Mincraft PE (payant), avec le logiciel Racoon (http://www.onyxbits.de/raccoon/). Il reste à savoir ce que fait Racoon différemment de gplaycli.

**Comment by craftyguy** [comment]
Sorry, I only know English, but I would also really like to see this. I have paid apps associated with the credentials I am using with gplaycli, and it would be amazing to be able to pull down updates using those credentials.

**Comment by roblabla** [comment]
A very quick look into racoon reveals this : 

https://github.com/onyxbits/Raccoon/blob/master/src/main/java/de/onyxbits/raccoon/io/FetchService.java#L68 Seems to be the function that handles downloading an app based on appid. It figures out if it is paid or not, and if it is paid, it calls https://github.com/onyxbits/Raccoon/blob/master/src/main/java/com/akdeniz/googleplaycrawler/GooglePlayAPI.java#L359

It seems that the only differing path in raccoon is the way it gets the "app delivery". If it is an unpaid app, it "purchases" it, which gives it the delivery status. If it's a paid app, it instead queries the app service for an app delivery.

Implementation should be fairly straightforward. For our purposes, we'll have to add a method (`delivery`) or an option to download in https://github.com/matlink/gplaycli/blob/master/ext_libs/googleplay_api/googleplay.py  and then call it in gplaycli when the app is detected as being paid.

**Comment by matlink** [comment]
Feel free to PR!

**Comment by roblabla** [comment]
I did, see #53

On May 5, 2017 7:50:13 PM GMT+02:00, Matlink <notifications@github.com> wrote:
>Feel free to PR!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/matlink/gplaycli/issues/8#issuecomment-299531292

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matlink** [comment]
Great I didn't see it. I'll need to test it before merging.

**Comment by psycholyzern** [comment]
Any news on this?

**Comment by roblabla** [comment]
@psycholyzern #53 still works, if you want to try it.

**Comment by psycholyzern** [comment]
Actually I have been Googling on how to merge those pr into the master. I am no expert, so I failed and don't know what I should do. Then I asked here. 😅

**Comment by matlink** [comment]
I'm currently working on it, I need a bit more info before merging. I've pulled it into a new branch called `paidapps` for now. You can clone it.

**Comment by psycholyzern** [comment]
Thanks a lot for that. I tested and it works.
![](http://i.imgur.com/phnwBrX.jpg)

Tested with:
- Mx Player Pro: https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.pro
- Tasker: https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

Also, ```-P``` helps me search the apps. Without ```-P``` flags, those paid apps won't show up in the result.
