### ISSUE TITLE
Make gplaycli reuse the auth token

### ISSUE THREAD

**Issue by rehmatworks** [matlink/gplaycli#81]
Token dispenser's created tokens are working like a charm with gplaycli but if you can make a modification in gplaycli to make it reuse the tokens, that'd be great. Currently, tokens are requested for each APK download request but if tokens are reused, then we can reduce the number of unnecessary hits to Google servers.

**Comment by matlink** [comment]
tag 0.2.7 (https://github.com/matlink/gplaycli/releases/tag/0.2.7) should do the trick.

**Comment by rehmatworks** [comment]
Thank you so much for your great efforts.

**Comment by matlink** [comment]
However, I don't know how long a token is valid. For now, gplaycli only cache the first token it gets and uses it for every communication across gplaycli invocations. 
I'll need to check if the token is expired before using it, but I don't know how to do it yet.

**Comment by archon810** [comment]
What if you fake the token and see what happens? I'm guessing something like BadAuthentication, or any error code response would be a good indication of the need to refresh.

**Comment by matlink** [comment]
Yes it gives me a bad header for the response. There should be documentation somewhere. 
-- 
Matlink

**Comment by NoMore201** [comment]
@matlink  
> I'll need to check if the token is expired before using it, but I don't know how to do it yet.

Well, you could simply login with that saved token, until it throws Authentication Error. In that case, refresh the token. Could this be an easy solution?

**Comment by matlink** [comment]
Are we sure that the error will be a bad authentication?

**Comment by matlink** [comment]
okay that should implement it c4cafabb8d4a3b4f17e785dbb6b4373680327931
