### ISSUE TITLE
Retries field required in config file

### ISSUE THREAD

**Issue by plroman** [matlink/gplaycli#82]
I believe the latest release message [1] for version 0.2.7 is incomplete, it says the token field is required in the config file, but it doesn't talk about the retries field, which also seems required.

I updated to version 0.2.7 via pip, added the token field in my config file as said in the release message, and got this error:
> Traceback (most recent call last):
>   File "/usr/local/bin/gplaycli", line 523, in <module>
>     main()
>   File "/usr/local/bin/gplaycli", line 490, in main
>     cli = GPlaycli(args, args.config)
>   File "/usr/local/bin/gplaycli", line 94, in __init__
>     self.retries = int(self.config["retries"])
> KeyError: 'retries'

Fixed by adding a retries field to my config file.
Could you please update the release message or maybe define a hard-coded default value for this parameter?

Cheers.

[1] https://github.com/matlink/gplaycli/releases/tag/0.2.7

**Comment by matlink** [comment]
Well the retries option is here since the previous version to quick fix some bad Auth issues. How with pip did you get your configuration file?

**Comment by plroman** [comment]
I don't remember, I may have copied it from the pip directory or from the github page.
The provided credentials given by pip is here `/usr/local/lib/python2.7/dist-packages/root/.config/gplaycli/credentials.conf` (debian stretch).

Since the release message mentioned the required token field, I just thought it could mention the retries field as well. It's not a big problem.

**Comment by matlink** [comment]
Well I should use default values when some fields are missing.
