### ISSUE TITLE
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)

### ISSUE THREAD

**Issue by archon810** [matlink/gplaycli#83]
- [OpenSUSE 42.1 ] Operating System (ie Ubuntu 16.04)
- [2.7] Python version when running `gplaycli` (should be 2.7 for now)
- [gplaycli doesn't run, but latest as of today or so ] GPlayCli version via `gplaycli -v`
- [`virtualenv env; ./env/bin/pip install -r requirements.txt`] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

```
./env/bin/python gplaycli.py
Traceback (most recent call last):
  File "gplaycli.py", line 27, in <module>
    from ext_libs.googleplay_api.googleplay import GooglePlayAPI  # GooglePlayAPI
  File "DIR/ext_libs/googleplay_api/googleplay.py", line 26, in <module>
    requests.post(conn_test_url, verify=ssl_verify)
  File "DIR/env/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "DIR/env/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "DIR/env/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "DIR/env/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "DIR/env/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

Any idea why it's doing that?

**Comment by archon810** [comment]
Looking at the code of googleplay.py, it's using `ssl_verify="/etc/ssl/certs/ca-certificates.crt"` which doesn't exist on my system.

**Comment by archon810** [comment]
Alright, I figured it out. The file on OpenSUSE is /var/lib/ca-certificates/ca-bundle.pem. Now gplaycli starts.

What's the best way to handle such differences in location besides modifying the source code? Maybe make it a config variable, defaulting to `/etc/ssl/certs/ca-certificates.crt` but with the ability to get customized in credentials.conf? Which really should by now be called config.conf or something.

**Comment by matlink** [comment]
Well I'm faced to a dilemma: `requests` has no cross-plateform way to point to CA bundle. It happens, even with `verify=True`, that requests throw `SSLError` on some platforms (#37).

**Comment by matlink** [comment]
However, I tried installing `gplaycli` in OpenSUSE 42.2, and everything is fine (I can search with `gplaycli`). So the `ssl_verify=True` should work in OpenSUSE.
If I recall well, I've put the CA bundle path for the old versions of debian where `ssl_verify=True` didn't work.

**Comment by archon810** [comment]
I'm on OpenSUSE 42.1, so maybe it's something between those two. Waiting for 42.3 to be released at the end of July to upgrade.

I've changed the hardcoded path for now. Another alternative is just creating a symlink on my machines.

**Comment by matlink** [comment]
We need to find something more viable. Because when you will upgrade, you'll have to set it again.

**Comment by archon810** [comment]
Currently, we modified gplaycli so heavily that we'll have to merge any upstream changes anyway, so it's not a big concern. Though a symlink would resolve this permanently.

**Comment by matlink** [comment]
Fine, close if you think it's resolved

**Comment by archon810** [comment]
I mean, I'm fine with is either way, but if you want to make an improvement for others and make this a configurable value, I can keep it open.

**Comment by matlink** [comment]
I don't know if having this as configurable is a good idea, I fear that it will confuse some people. Plus, it's a kind of security issue since a user wide configuration file would be more easily writable for someone else than a root wide CA bundle.

**Comment by matlink** [comment]
Maybe it should be a good idea to use certifi python package https://pypi.python.org/pypi/certifi
