### ISSUE TITLE
Always get the same results when searching

### ISSUE THREAD

**Issue by 0uro** [matlink/gplaycli#9]
Hello,

I installed it in a debian chroot following your instructions and I got a strange output ; everytime it spits out the exact same list of apps completely regardless of what I provide in --search

gplaycli -s firefox
Title                           Creator          Size     Downloads   Last Update    AppID                                          Version  Rating  
LinkPush                        Connor Dunn      17.2KB   50 000+    7 juin 2010    uk.co.connorhd.android.linkpush                2        4.38    
Market Update Helper            Titanium Track   10.5KB   500 000+   12 févr. 2013 com.keramidas.MarketUpdateHelper               3        4.12    
PBrowser internet browser FREE  OurMedia         1.4MB    5 000+     24 févr. 2014 appinventor.ai_PieterBernabei.InternetBrowser  1        4.23    
WebSharingLite (File Manager)   NextApp, Inc.    2.0MB    500 000+   23 janv. 2014  nextapp.websharing                             2014     4.43    
Bookmark Sort & Backup          happydroid       173.4KB  100 000+   17 sept. 2012  com.happydroid.bookmarks                       49       4.17    
Network Speed                   pt               43.0KB   500 000+   29 avr. 2012   netspeed.pt                                    8        4.39    
Stock Photo Power Search        Imba Software    285.1KB  10 000+    26 juin 2012   com.stockphotofeeds.msp                        3        3.59    
WiFi Keyboard                   Ivan Volosyuk.   91.1KB   500 000+   9 juin 2013    com.volosyukivan                               30       4.33    
Unified Remote                  Unified Intents  1.1MB    1 000 000+6 août 2015   com.Relmtech.Remote                            63       4.46  

I checked the credential settings many times and the android id too...

**Comment by matlink** [comment]
Weird. Can you clone the repo and test with a `./gplaycli.py -s firefox` ?

**Comment by 0uro** [comment]
Cloned again and get same results.
I just noticed my explanations were not very precise.

When I user different search patterns I get different results, but never what I'm looking for (IE for firefox).
It's kinda topic-related results, but I never find what I'm looking for.
I tried "candy crush", "firefox", "dolphin browser", "poweramp" etc...

Here's the output for poweramp : 

./gplaycli -s poweramp
Title                         Creator         Size     Downloads    Last Update    AppID                                Version  Rating  
Batterie - Battery            MacroPinch      1.9MB    10 000 000+5 juin 2015    com.macropinch.pearl                 38       4.48    
MixZing Music Player          MixZing         3.6MB    5 000 000+ 4 mai 2015     com.mixzing.basic                    46       4.37    
MortPlayer Music              Mirko Schenk    2.2MB    1 000 000+ 8 avr. 2013    de.stohelit.folderplayer             100017   4.49    
tinyPlayer                    C0br4Softworks  120.1KB  100 000+    28 janv. 2015  com.c0br4.tinyplayer                 22       4.21    
DroidWall - Android Firewall  Rodrigo ZR      310.8KB  1 000 000+ 9 déc. 2011   com.googlecode.droidwall.free        157      4.37    
Phantom Music Control         Jan Gruncl      1.4MB    500 000+    4 août 2013   cz.jhg.musiccontrolwidget            1670     3.80    
Peek Icon Pack                Jack Donegan    1.8MB    100 000+    13 mars 2014   jack.peek.iconpack                   5        3.44    
MortPlayer Audio Books        Mirko Schenk    2.3MB    1 000 000+ 25 juil. 2012  de.stohelit.audiobookplayer          100005   4.46    
Subsonic Music Streamer       Sindre Mehus    824.9KB  100 000+    31 août 2014  net.sourceforge.subsonic.androidapp  47       4.33    

Maybe has it something to do with the priority of results

**Comment by matlink** [comment]
What kind of credentials are you using ? The ones that are provided with the package or your own ones ?

**Comment by 0uro** [comment]
My personnal own ones, using my phone android ID

**Comment by matlink** [comment]
Could you try with the ones of the package and see if results are the same ?

**Comment by 0uro** [comment]
It works with those provided.
I noticed I received those safety notifications from google, "new connection on android device". Maybe is this related to some security from google

**Comment by matlink** [comment]
Well, if the mail doesn't say 'the connection has been blocked', nothing's bad.
What is the model of your phone ?

**Comment by 0uro** [comment]
Nexus 4 running cyanogenmod 12.1 nightly

**Comment by matlink** [comment]
Weird, does not seem to be an old one... Either use the provided credentials, or use yours and generate a new androidID (check Readme).

**Comment by matlink** [comment]
Can't do much from here, since it seems to be related to the androidID you're using.

**Comment by 0uro** [comment]
Of course, I'm exploring the account security settings.
Is it risky to use the default account ? I mean if many people start using it it could end up making google shutting that account down, and anyone can change the password too of course

**Comment by matlink** [comment]
Not risky for you, they could shut it down, and anyone can change the
password. But in both case, that doesn't matter : I can recreate an
account, and I can recover the password.

Le 27/08/2015 20:52, 0uro a écrit :
>
> Of course, I'm exploring the account security settings.
> Is it risky to use the default account ? I mean if many people start
> using it it could end up making google shutting that account down, and
> anyone can change the password too of course
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matlink/gplaycli/issues/9#issuecomment-135521543>.
>

-- 
Matlink - Sysadmin matlink.fr

**Comment by 0uro** [comment]
Okay nice :)
Really great work btw, we only need an auto-update feature ^^

**Comment by matlink** [comment]
What do you mean by auto-update ?

**Comment by 0uro** [comment]
Yep that kind of things.
Using the combo gplaycli + gplayweb + fdroid, means checking yourself in gplayweb for new updates and download them if necessary.

Not aiming the per-device google approach (which means modifying fdroid too), but cron job would be a simple way to simply daily check updates and automagically download them so fdroid can do the magic :)

**Comment by matlink** [comment]
Can you add an issue for it ? thanks :)

Le 27/08/2015 23:05, 0uro a écrit :
>
> Yep that kind of things.
> Using the combo gplaycli + gplayweb + fdroid, means checking yourself
> in gplayweb for new updates and download them if necessary.
>
> Not aiming the per-device google approach (which means modifying
> fdroid too), but cron job would be a simple way to simply daily check
> updates and automagically download them so fdroid can do the magic :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matlink/gplaycli/issues/9#issuecomment-135554900>.
>

-- 
Matlink - Sysadmin matlink.fr

**Comment by 0uro** [comment]
done :)
