### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by sepehr103** [matlink/gplaycli#90]
the link which generated the token no longer works!

**Comment by matlink** [comment]
Yes, I'm aware of it, but it seems related to token dispenser because I tried with another Google account and it didn't solve the problem.

**Comment by sepehr103** [comment]
can I be of any help? or do you have any Idea on what's the solution to this problem?

**Comment by matlink** [comment]
Well I asked the creator of token dispenser. 
If you're able to deploy a token dispenser on your own and use it with gplaycli, it could comfort me on finding what's wrong.

**Comment by sepehr103** [comment]
also the normal login(token=false) is not working too!

**Comment by matlink** [comment]
Yes Google has changed its api so I need some code modifications to handle ghat5

**Comment by sepehr103** [comment]
I deployed the server myself and its working:
http://185.162.235.209:8080/token-ac2dm/email/dozd.dozdian.1@gmail.com
btw, can I have your email, I hate to communicate with you in public :)

**Comment by matlink** [comment]
Many thanks. I'll check what's wrong soon. It comes from my side then.

**Comment by sepehr103** [comment]
or maybe, the problem is with some google accounts being banned or something?

**Comment by matlink** [comment]
I created a new one. Maybe my IP is banned.

**Comment by matlink** [comment]
Okay that came from my side. No banned IP, just have to reconfigured some new accounts.
