### ISSUE TITLE
python-enum required?

### ISSUE THREAD

**Issue by jr3074** [matlink/gplaycli#91]
error after install using pip=

> File "/usr/local/bin/gplaycli", line 25, in <module>
    from enum import IntEnum

**Comment by matlink** [comment]
Please provide those informations:

- [ ] Operating System (ie Ubuntu 16.04)
- [ ] Python version when running `gplaycli` (should be 2.7 for now)
- [ ] GPlayCli version via `gplaycli -v`
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

**Comment by jr3074** [comment]
debian jessie
latest gplaycli
python 2.7.9
using pip install gplaycli

**Comment by matlink** [comment]
Normally `pip install gplaycli` installs `enum34` via `cryptography`
