### ISSUE TITLE
Credentials not working

### ISSUE THREAD

**Issue by dillrich** [matlink/gplaycli#94]
Please provide those informations:

- [x] Operating System (ie Ubuntu 16.04)
 Linux Mint
- [x] Python version when running `gplaycli` (should be 2.7 for now)
2.7
- [x] GPlayCli version via `gplaycli -v`
0.2.10
- [x] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
git clone
----
output:
$ python gplaycli.py -s twitter
Traceback (most recent call last):
  File "gplaycli.py", line 553, in <module>
    main()
  File "gplaycli.py", line 523, in main
    success, error = cli.connect_to_googleplay_api()
  File "gplaycli.py", line 181, in connect_to_googleplay_api
    self.raw_search(list(), 'firefox', 1)
  File "gplaycli.py", line 368, in raw_search
    return self.playstore_api.search(search_string, nb_results=nb_results).doc
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 199, in search
  File "build/bdist.linux-x86_64/egg/ext_libs/googleplay_api/googleplay.py", line 183, in executeRequestApi2
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 583, in FromString
    message.MergeFromString(s)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

**Comment by dillrich** [comment]
you can close this....I didn't set up token right for my device / username and password.  After generating my own token I don't get the same error message.

**Comment by ColtonPhillips** [comment]
I am also getting this issue but I am naive on how to generate a token as dillrich says.

**Comment by matlink** [comment]
you don't need to generate a token yourself. Can you post the gplaycli.conf file here? without your password if you set one.

**Comment by eighthave** [comment]
My gplaycli was working, but now I'm getting this error too, on elementaryOS (based on Ubuntu 16.04) using 0.2.10.  This is my _~/.config/gplaycli/gplaycli.conf_:
```
[Credentials]
gmail_address=myfakeusername@gmail.com
gmail_password=myfakepassword
android_ID=01234567890abcde
language=en_US
```

**Comment by eighthave** [comment]
Switching to the default _/etc/gplaycli/gplaycli.conf_ fixed it for me.

**Comment by matlink** [comment]
`/etc/gplaycli/gplaycli.conf` is using tokens I guess. Could you check?
I bet it's an issue with your credentials. Did you enabled 2FA?

**Comment by eighthave** [comment]
yes, it is using tokens.  I did not enable 2FA.

**Comment by eighthave** [comment]
I just logged into Google Calendar with those credentials, worked fine.

**Comment by matlink** [comment]
Yeah, looks like Google has definitely removed plaintext authentication :(
Check https://github.com/matlink/gplaycli/issues/80#issuecomment-313797511

**Comment by CMCDragonkai** [comment]
Just a question, what should the gplaycli.conf look like if you know your own email, password and device id and don't want to work around tokens? Or is tokens now mandatory?

**Comment by matlink** [comment]
Put your credentials and android_id and set token=False.
