### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sepehr103** [matlink/gplaycli#96]
its no longer working for me, do you guys have the same issue?

**Comment by matlink** [comment]
"Not working" is an issue, it's a feature.
Joke aside, if I made a template for issue, it's not for nothing!
Please provide those informations:

- [ ] Operating System (ie Ubuntu 16.04)
- [ ] Python version when running `gplaycli` (should be 2.7 for now)
- [ ] GPlayCli version via `gplaycli -v`
- [ ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

**Comment by peterstory** [comment]
Perhaps related to some changes on Google's side:
http://blog.onyxbits.de/raccoon-app-search-works-download-doesnt-658/

**Comment by archon810** [comment]
Also related: https://github.com/dweinstein/node-google-play/issues/68

**Comment by matlink** [comment]
I can download `com.twitter.android` using gplaycli in virtualenv with `pip install gplaycli`.
So this thread need more informations.

**Comment by jr3074** [comment]
works great here, there is no issue about it, maybe partial user? or this app has different method to download the apk
@archon810

**Comment by peterstory** [comment]
I've also successfully downloaded APKs using token authentication. However, I did notice that attempting to download with `token=False` (using `gmail_address` and `gmail_password`) is still broken. Perhaps @matlink should add a warning to the README?
