### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by abhijeet0007** [matlink/gplaycli#97]
i have found this kind of issu. please reslove.

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /fdfe/bulkDetails (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4470960a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Please provide those informations:

- [Ubuntu 16.04 ] Operating System (ie Ubuntu 16.04)
- [ Python 2.7.12] Python version when running `gplaycli` (should be 2.7 for now)
- [GPlayCli version 0.2.12 ] GPlayCli version via `gplaycli -v`
- [apt install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...

**Comment by matlink** [comment]
Try to connect manually to android.clients.google.com : 
`telnet android.clients.google.com 443`
and give me the output.

**Comment by abhijeet0007** [comment]
root@localhost:~# telnet android.clients.google.com 443
Trying 172.217.11.14...
Connected to android.l.google.com.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by archon810** [comment]
Connects fine here. Must be a local issue, or they've blocked you.
